#!/usr/bin/env python3
"""Build the optuna_hyperparameter_guide.ipynb notebook."""
import sys as _sys
import os as _os


def _find_repo_root(start_dir):
    current = _os.path.abspath(start_dir)
    while True:
        if _os.path.exists(_os.path.join(current, "manage.sh")) and _os.path.isdir(_os.path.join(current, "kaggle_portfolio")):
            return current
        parent = _os.path.dirname(current)
        if parent == current:
            return _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
        current = parent


_sys.path.insert(0, _find_repo_root(_os.path.dirname(_os.path.abspath(__file__))))
from kaggle_portfolio.shared.build_utils import md, code, write_notebook

cells = []

# ── Cell 1: Title Banner ──────────────────────────────────────────────────────
cells.append(md(
'# <center>Optuna: Hyperparameter Optimization for Kaggle</center>\n'
'\n'
'<center>\n'
'\n'
'![Python](https://img.shields.io/badge/Python-3.10-blue?logo=python&logoColor=white)\n'
'![Optuna](https://img.shields.io/badge/Optuna-3.x-blueviolet)\n'
'![XGBoost](https://img.shields.io/badge/XGBoost-2.0-green)\n'
'![LightGBM](https://img.shields.io/badge/LightGBM-4.1-purple)\n'
'![scikit-learn](https://img.shields.io/badge/scikit--learn-1.3-orange?logo=scikit-learn)\n'
'![License](https://img.shields.io/badge/License-MIT-red)\n'
'\n'
'</center>\n'
'\n'
'---\n'
'\n'
'**Author:** Lorenzo Scaturchio  \n'
'**Last Updated:** February 2026  \n'
'**Kernel Version:** 1.0\n'
'\n'
'> *"Hyperparameter tuning is where competitions are won or lost. Optuna is the sharpest tool in the box."*  \n'
'> -- Kaggle Grandmaster Handbook\n'
'\n'
'---'
))

# ── Cell 2: TL;DR ─────────────────────────────────────────────────────────────
cells.append(md(
'## TL;DR\n'
'\n'
'This notebook is a **complete, practical guide** to hyperparameter optimization with Optuna -- the framework used by top Kaggle competitors worldwide.\n'
'\n'
'| Method | Strategy | Sample Efficiency | Best For |\n'
'|--------|----------|------------------|----------|\n'
'| **Grid Search** | Exhaustive enumeration | Very Low | Small, discrete spaces |\n'
'| **Random Search** | Uniform random sampling | Low | Baseline exploration |\n'
'| **Bayesian (Optuna/TPE)** | Probabilistic surrogate model | **High** | Any continuous/mixed space |\n'
'| **CMA-ES** | Evolution strategy | High | High-dim continuous spaces |\n'
'\n'
'**Key takeaway:** Optuna\'s TPE sampler typically finds results in 50 trials that Random Search needs 500+ trials to match.\n'
'\n'
'If you find this notebook useful, please consider giving it an **upvote** -- it helps others discover it!'
))

# ── Cell 3: Table of Contents ─────────────────────────────────────────────────
cells.append(md(
'## Table of Contents\n'
'\n'
'1. [Why Hyperparameter Optimization Matters](#1)\n'
'2. [Setup & Data](#2)\n'
'3. [Optuna Basics: Your First Study](#3)\n'
'4. [TPE Sampler: How It Works](#4)\n'
'5. [CMA-ES Sampler: Continuous Spaces](#5)\n'
'6. [Pruning: Kill Unpromising Trials Early](#6)\n'
'7. [Visualizing Studies](#7)\n'
'8. [XGBoost + Optuna: Production Pipeline](#8)\n'
'9. [LightGBM + Optuna: Production Pipeline](#9)\n'
'10. [Sklearn Integration: OptunaSearchCV](#10)\n'
'11. [Multi-Objective Optimization](#11)\n'
'12. [Hyperparameter Importance](#12)\n'
'13. [Production Tips for Kaggle](#13)\n'
'\n'
'---'
))

# ── Cell 4: Section 1 header ──────────────────────────────────────────────────
cells.append(md(
'<a id="1"></a>\n'
'## 1. Why Hyperparameter Optimization Matters\n'
'\n'
'### The Cost of Bad Hyperparameters\n'
'\n'
'Machine learning models are extraordinarily sensitive to hyperparameter choices. Consider a gradient-boosted tree:\n'
'\n'
'- **Learning rate**: span of 4 orders of magnitude (0.001 to 1.0)\n'
'- **Max depth**: integer from 2 to 12\n'
'- **Subsample**: continuous from 0.5 to 1.0\n'
'- **colsample_bytree**: continuous from 0.5 to 1.0\n'
'- **reg_alpha, reg_lambda**: log-scale over 6 orders of magnitude each\n'
'\n'
'A naive grid search over just 5 values per parameter = **5^6 = 15,625 evaluations**. At 30 seconds each, that is 130 hours. Kaggle kernels give you 12.\n'
'\n'
'### Comparison of Strategies\n'
'\n'
'| Strategy | Trials to find top-5% params | Wall time (est.) | Handles dependencies? |\n'
'|----------|-------------------------------|------------------|-----------------------|\n'
'| Grid Search | 10,000+ | Days | No |\n'
'| Random Search | 200-500 | Hours | Partially |\n'
'| **Bayesian (Optuna)** | **50-100** | **Minutes** | **Yes** |\n'
'\n'
'### Why Bayesian Optimization Wins\n'
'\n'
'Bayesian optimization maintains a **probabilistic surrogate model** of the objective function. After each trial:\n'
'\n'
'1. The model is updated with the new (params, score) observation\n'
'2. An **acquisition function** (EI -- Expected Improvement) selects the next point to evaluate\n'
'3. Points in promising regions are sampled more frequently\n'
'\n'
'This is fundamentally different from random search: instead of sampling blindly, the algorithm *learns* which regions of the search space are worth exploring.\n'
'\n'
'**Optuna\'s TPE (Tree-structured Parzen Estimator)** extends this to handle:\n'
'- Mixed integer/float/categorical parameters\n'
'- Conditional search spaces (e.g., "only tune dropout if using neural net")\n'
'- Parallel execution across multiple cores or machines\n'
'\n'
'---'
))

# ── Cell 5: Section 2 header ──────────────────────────────────────────────────
cells.append(md(
'<a id="2"></a>\n'
'## 2. Setup & Data\n'
'\n'
'Install Optuna and its integration package, then load the breast cancer dataset as our benchmark throughout this guide.'
))

# ── Cell 6: Setup code ────────────────────────────────────────────────────────
cells.append(code(
'!pip install optuna optuna-integration -q\n'
'\n'
'import optuna\n'
'import numpy as np\n'
'import pandas as pd\n'
'import matplotlib.pyplot as plt\n'
'import matplotlib.gridspec as gridspec\n'
'import seaborn as sns\n'
'import time\n'
'import warnings\n'
'\n'
'from sklearn.datasets import load_breast_cancer\n'
'from sklearn.model_selection import (\n'
'    cross_val_score, StratifiedKFold, train_test_split\n'
')\n'
'from sklearn.ensemble import RandomForestClassifier\n'
'from sklearn.metrics import roc_auc_score\n'
'import xgboost as xgb\n'
'import lightgbm as lgb\n'
'\n'
'warnings.filterwarnings("ignore")\n'
'optuna.logging.set_verbosity(optuna.logging.WARNING)\n'
'\n'
'# Reproducibility\n'
'np.random.seed(42)\n'
'\n'
'# Styling\n'
'plt.style.use("seaborn-v0_8-whitegrid")\n'
'PALETTE = ["#4C72B0", "#DD8452", "#55A868", "#C44E52", "#8172B2"]\n'
'\n'
'# Dataset: breast cancer (binary classification, 569 samples, 30 features)\n'
'X, y = load_breast_cancer(return_X_y=True)\n'
'feature_names = load_breast_cancer().feature_names\n'
'print(f"Dataset shape : {X.shape}")\n'
'print(f"Positive class: {y.mean():.2%}")\n'
'print(f"\\nFeatures: {list(feature_names[:5])} ...")'
))

# ── Cell 7: Section 3 header ──────────────────────────────────────────────────
cells.append(md(
'<a id="3"></a>\n'
'## 3. Optuna Basics: Your First Study\n'
'\n'
'### Core Vocabulary\n'
'\n'
'| Term | Definition |\n'
'|------|------------|\n'
'| **Trial** | A single call to the objective function with one set of hyperparameters |\n'
'| **Study** | A collection of trials; persists the optimization history |\n'
'| **Objective** | The Python function you want to maximize or minimize |\n'
'| **Sampler** | The algorithm that proposes new parameter values (TPE, CMA-ES, Random) |\n'
'| **Pruner** | An early-stopping rule that kills unpromising trials mid-run |\n'
'\n'
'### Suggest API\n'
'\n'
'Inside the objective, use `trial.suggest_*` to declare hyperparameters:\n'
'\n'
'```python\n'
'trial.suggest_int("n_estimators", 50, 300)          # integer\n'
'trial.suggest_float("learning_rate", 1e-4, 0.3, log=True)  # float, log scale\n'
'trial.suggest_float("dropout", 0.1, 0.5)            # float, linear scale\n'
'trial.suggest_categorical("criterion", ["gini", "entropy"])  # categorical\n'
'```\n'
'\n'
'The `log=True` flag is **critical** for parameters like learning rates that span multiple orders of magnitude -- it ensures the sampler allocates equal probability mass to each order of magnitude rather than biasing toward large values.'
))

# ── Cell 8: First study code ──────────────────────────────────────────────────
cells.append(code(
'def objective(trial):\n'
'    """Simple RandomForest objective for breast cancer classification."""\n'
'    n_estimators = trial.suggest_int("n_estimators", 50, 300)\n'
'    max_depth = trial.suggest_int("max_depth", 3, 10)\n'
'    min_samples_split = trial.suggest_int("min_samples_split", 2, 20)\n'
'    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)\n'
'    max_features = trial.suggest_categorical("max_features", ["sqrt", "log2", None])\n'
'\n'
'    clf = RandomForestClassifier(\n'
'        n_estimators=n_estimators,\n'
'        max_depth=max_depth,\n'
'        min_samples_split=min_samples_split,\n'
'        min_samples_leaf=min_samples_leaf,\n'
'        max_features=max_features,\n'
'        random_state=42,\n'
'        n_jobs=-1,\n'
'    )\n'
'    score = cross_val_score(\n'
'        clf, X, y, cv=5, scoring="roc_auc", n_jobs=-1\n'
'    ).mean()\n'
'    return score\n'
'\n'
'\n'
'# Create and run a study\n'
'study = optuna.create_study(direction="maximize", study_name="rf_baseline")\n'
'study.optimize(objective, n_trials=50, show_progress_bar=True)\n'
'\n'
'print(f"\\nBest trial : #{study.best_trial.number}")\n'
'print(f"Best ROC-AUC: {study.best_value:.4f}")\n'
'print(f"Best params :")\n'
'for k, v in study.best_params.items():\n'
'    print(f"  {k}: {v}")'
))

# ── Cell 9: Trials dataframe ──────────────────────────────────────────────────
cells.append(code(
'# Inspect all trials as a DataFrame\n'
'trials_df = study.trials_dataframe()\n'
'print(f"Columns: {list(trials_df.columns)}\\n")\n'
'\n'
'# Sort by value and display top 5\n'
'top5 = trials_df.sort_values("value", ascending=False).head(5)\n'
'display_cols = ["number", "value", "params_n_estimators", "params_max_depth",\n'
'                "params_min_samples_split", "params_min_samples_leaf", "params_max_features"]\n'
'print("Top 5 trials:")\n'
'print(top5[display_cols].to_string(index=False))'
))

# ── Cell 10: Section 4 header ─────────────────────────────────────────────────
cells.append(md(
'<a id="4"></a>\n'
'## 4. TPE Sampler: How It Works\n'
'\n'
'### Tree-structured Parzen Estimator (TPE)\n'
'\n'
'TPE is Optuna\'s default sampler and the reason it outperforms random search. The algorithm works as follows:\n'
'\n'
'1. **Split trials** into "good" (top gamma%) and "bad" (bottom 1-gamma%) based on objective value\n'
'2. **Fit two density estimators**: `l(x)` over good trials, `g(x)` over bad trials\n'
'3. **Sample new candidate** by maximizing `l(x) / g(x)` (Expected Improvement proxy)\n'
'4. **Evaluate** the candidate and update the model\n'
'\n'
'This means TPE *learns the distribution of good hyperparameters* and concentrates sampling there.\n'
'\n'
'### TPE vs Random Search: Head-to-Head\n'
'\n'
'Let\'s run both with the same budget and compare convergence speed.'
))

# ── Cell 11: TPE vs Random comparison ────────────────────────────────────────
cells.append(code(
'# Random baseline\n'
'random_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.RandomSampler(seed=42),\n'
'    study_name="rf_random",\n'
')\n'
'random_study.optimize(objective, n_trials=60, show_progress_bar=False)\n'
'\n'
'# TPE (default)\n'
'tpe_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.TPESampler(seed=42),\n'
'    study_name="rf_tpe",\n'
')\n'
'tpe_study.optimize(objective, n_trials=60, show_progress_bar=False)\n'
'\n'
'# Plot convergence curves\n'
'fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n'
'\n'
'for study_obj, label, color in [\n'
'    (random_study, "Random Search", PALETTE[2]),\n'
'    (tpe_study, "TPE (Optuna)", PALETTE[0]),\n'
']:\n'
'    values = [t.value for t in study_obj.trials]\n'
'    best_so_far = pd.Series(values).cummax()\n'
'    axes[0].plot(best_so_far.values, label=label, color=color, linewidth=2.5)\n'
'    axes[1].plot(values, label=label, color=color, alpha=0.7, linewidth=1.5)\n'
'\n'
'axes[0].set_title("Best ROC-AUC Found So Far", fontsize=13, fontweight="bold")\n'
'axes[0].set_xlabel("Trial Number")\n'
'axes[0].set_ylabel("Best ROC-AUC")\n'
'axes[0].legend()\n'
'\n'
'axes[1].set_title("Per-Trial ROC-AUC (All Trials)", fontsize=13, fontweight="bold")\n'
'axes[1].set_xlabel("Trial Number")\n'
'axes[1].set_ylabel("ROC-AUC")\n'
'axes[1].legend()\n'
'\n'
'plt.suptitle("Random Search vs TPE Convergence", fontsize=15, fontweight="bold", y=1.02)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print(f"Random Search best: {random_study.best_value:.4f} (trial #{random_study.best_trial.number})")\n'
'print(f"TPE best          : {tpe_study.best_value:.4f} (trial #{tpe_study.best_trial.number})")'
))

# ── Cell 12: Section 5 header ─────────────────────────────────────────────────
cells.append(md(
'<a id="5"></a>\n'
'## 5. CMA-ES Sampler: Continuous Spaces\n'
'\n'
'### When to Use CMA-ES\n'
'\n'
'CMA-ES (Covariance Matrix Adaptation Evolution Strategy) is an evolutionary algorithm optimized for **high-dimensional, continuous** search spaces. Use it when:\n'
'\n'
'- Most hyperparameters are **floats** (not integers or categoricals)\n'
'- The space has **more than 5 dimensions**\n'
'- Parameters are **correlated** (e.g., learning_rate and n_estimators interact)\n'
'\n'
'CMA-ES maintains a **multivariate Gaussian** over the search space and adapts both the mean and covariance matrix based on successful candidates, naturally learning parameter correlations.\n'
'\n'
'### CMA-ES on a Float-Heavy XGBoost Space'
))

# ── Cell 13: CMA-ES code ──────────────────────────────────────────────────────
cells.append(code(
'def objective_continuous(trial):\n'
'    """XGBoost with float-heavy search space -- ideal for CMA-ES."""\n'
'    learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-1, log=True)\n'
'    subsample = trial.suggest_float("subsample", 0.5, 1.0)\n'
'    colsample_bytree = trial.suggest_float("colsample_bytree", 0.5, 1.0)\n'
'    reg_alpha = trial.suggest_float("reg_alpha", 1e-8, 1.0, log=True)\n'
'    reg_lambda = trial.suggest_float("reg_lambda", 1e-8, 1.0, log=True)\n'
'    gamma = trial.suggest_float("gamma", 0.0, 5.0)\n'
'    min_child_weight = trial.suggest_float("min_child_weight", 1.0, 10.0)\n'
'\n'
'    clf = xgb.XGBClassifier(\n'
'        learning_rate=learning_rate,\n'
'        subsample=subsample,\n'
'        colsample_bytree=colsample_bytree,\n'
'        reg_alpha=reg_alpha,\n'
'        reg_lambda=reg_lambda,\n'
'        gamma=gamma,\n'
'        min_child_weight=min_child_weight,\n'
'        n_estimators=100,\n'
'        eval_metric="auc",\n'
'        random_state=42,\n'
'        verbosity=0,\n'
'    )\n'
'    score = cross_val_score(\n'
'        clf, X, y, cv=5, scoring="roc_auc", n_jobs=-1\n'
'    ).mean()\n'
'    return score\n'
'\n'
'\n'
'# TPE on float space (baseline)\n'
'tpe_cont_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.TPESampler(seed=42),\n'
')\n'
'tpe_cont_study.optimize(objective_continuous, n_trials=60, show_progress_bar=False)\n'
'\n'
'# CMA-ES on float space\n'
'cmaes_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.CmaEsSampler(seed=42),\n'
')\n'
'cmaes_study.optimize(objective_continuous, n_trials=60, show_progress_bar=False)\n'
'\n'
'# Convergence comparison\n'
'fig, ax = plt.subplots(figsize=(11, 5))\n'
'for study_obj, label, color in [\n'
'    (tpe_cont_study, "TPE", PALETTE[0]),\n'
'    (cmaes_study, "CMA-ES", PALETTE[1]),\n'
']:\n'
'    values = [t.value for t in study_obj.trials]\n'
'    best_so_far = pd.Series(values).cummax()\n'
'    ax.plot(best_so_far.values, label=label, color=color, linewidth=2.5)\n'
'\n'
'ax.set_title("TPE vs CMA-ES on Continuous XGBoost Space", fontsize=13, fontweight="bold")\n'
'ax.set_xlabel("Trial Number")\n'
'ax.set_ylabel("Best ROC-AUC")\n'
'ax.legend()\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print(f"TPE best  : {tpe_cont_study.best_value:.4f}")\n'
'print(f"CMA-ES best: {cmaes_study.best_value:.4f}")\n'
'print(f"\\nCMA-ES best params:")\n'
'for k, v in cmaes_study.best_params.items():\n'
'    print(f"  {k}: {v:.6g}")'
))

# ── Cell 14: Section 6 header ─────────────────────────────────────────────────
cells.append(md(
'<a id="6"></a>\n'
'## 6. Pruning: Kill Unpromising Trials Early\n'
'\n'
'### What is Pruning?\n'
'\n'
'Pruning is **early stopping at the study level**: if a trial\'s intermediate scores are consistently below the median of completed trials, kill it and move on. This can reduce total compute by 30-70%.\n'
'\n'
'### MedianPruner\n'
'\n'
'The most common pruner in Optuna:\n'
'\n'
'```python\n'
'optuna.pruners.MedianPruner(\n'
'    n_startup_trials=5,   # run first N trials fully (cold start)\n'
'    n_warmup_steps=10,    # skip pruning for first N steps of each trial\n'
'    interval_steps=1,     # check pruning every N steps\n'
')\n'
'```\n'
'\n'
'### XGBoost Integration with Pruning Callback\n'
'\n'
'Optuna\'s integration package provides `XGBoostPruningCallback` which reports intermediate scores after each boosting round and asks Optuna whether to continue.'
))

# ── Cell 15: Pruning code ─────────────────────────────────────────────────────
cells.append(code(
'from sklearn.model_selection import train_test_split\n'
'\n'
'X_tr, X_val, y_tr, y_val = train_test_split(\n'
'    X, y, test_size=0.2, random_state=42, stratify=y\n'
')\n'
'\n'
'\n'
'def objective_with_pruning(trial):\n'
'    """XGBoost objective that supports Optuna pruning via callback."""\n'
'    params = {\n'
'        "n_estimators": 500,\n'
'        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),\n'
'        "max_depth": trial.suggest_int("max_depth", 3, 9),\n'
'        "subsample": trial.suggest_float("subsample", 0.6, 1.0),\n'
'        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),\n'
'        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 1.0, log=True),\n'
'        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 1.0, log=True),\n'
'        "eval_metric": "auc",\n'
'        "early_stopping_rounds": 30,\n'
'        "random_state": 42,\n'
'        "verbosity": 0,\n'
'    }\n'
'\n'
'    try:\n'
'        from optuna.integration import XGBoostPruningCallback\n'
'        callbacks = [XGBoostPruningCallback(trial, "validation_0-auc")]\n'
'    except ImportError:\n'
'        callbacks = []\n'
'\n'
'    clf = xgb.XGBClassifier(**params)\n'
'    clf.fit(\n'
'        X_tr, y_tr,\n'
'        eval_set=[(X_val, y_val)],\n'
'        verbose=False,\n'
'        callbacks=callbacks,\n'
'    )\n'
'    score = roc_auc_score(y_val, clf.predict_proba(X_val)[:, 1])\n'
'    return score\n'
'\n'
'\n'
'# Without pruning\n'
'no_prune_study = optuna.create_study(direction="maximize")\n'
't0 = time.time()\n'
'no_prune_study.optimize(objective_with_pruning, n_trials=30, show_progress_bar=False)\n'
'no_prune_time = time.time() - t0\n'
'\n'
'# With MedianPruner\n'
'pruning_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    pruner=optuna.pruners.MedianPruner(\n'
'        n_startup_trials=5,\n'
'        n_warmup_steps=15,\n'
'    ),\n'
')\n'
't0 = time.time()\n'
'pruning_study.optimize(objective_with_pruning, n_trials=30, show_progress_bar=False)\n'
'prune_time = time.time() - t0\n'
'\n'
'n_pruned = sum(\n'
'    1 for t in pruning_study.trials\n'
'    if t.state == optuna.trial.TrialState.PRUNED\n'
')\n'
'print(f"=== Without Pruning ===")\n'
'print(f"  Best AUC  : {no_prune_study.best_value:.4f}")\n'
'print(f"  Wall time : {no_prune_time:.1f}s")\n'
'print(f"\\n=== With MedianPruner ===")\n'
'print(f"  Best AUC  : {pruning_study.best_value:.4f}")\n'
'print(f"  Wall time : {prune_time:.1f}s")\n'
'print(f"  Pruned    : {n_pruned}/{len(pruning_study.trials)} trials ({n_pruned/len(pruning_study.trials):.0%})")\n'
'print(f"  Speedup   : {no_prune_time/max(prune_time,1):.1f}x")'
))

# ── Cell 16: Section 7 header ─────────────────────────────────────────────────
cells.append(md(
'<a id="7"></a>\n'
'## 7. Visualizing Studies\n'
'\n'
'Optuna ships with a rich visualization module built on **Plotly**. These plots are interactive and render natively in Kaggle notebooks.\n'
'\n'
'| Plot | Purpose |\n'
'|------|---------|\n'
'| `plot_optimization_history` | Track best value over trials |\n'
'| `plot_slice` | How each param affects the objective |\n'
'| `plot_contour` | 2D interaction between two params |\n'
'| `plot_parallel_coordinate` | All params vs objective in one view |\n'
'| `plot_param_importances` | fANOVA importance ranking |\n'
'| `plot_edf` | Empirical distribution of trial values |'
))

# ── Cell 17: Visualization code ───────────────────────────────────────────────
cells.append(code(
'# We use the tpe_study from Section 3 for all visualizations\n'
'\n'
'# 1. Optimization history\n'
'fig = optuna.visualization.plot_optimization_history(tpe_study)\n'
'fig.update_layout(title="Optimization History (TPE Study)", height=400)\n'
'fig.show()\n'
'\n'
'# 2. Slice plot -- how each param affects objective\n'
'fig = optuna.visualization.plot_slice(tpe_study)\n'
'fig.update_layout(title="Slice Plot: Per-Parameter Effect on ROC-AUC", height=400)\n'
'fig.show()\n'
'\n'
'# 3. Contour: interaction between n_estimators and max_depth\n'
'fig = optuna.visualization.plot_contour(\n'
'    tpe_study, params=["n_estimators", "max_depth"]\n'
')\n'
'fig.update_layout(title="Contour: n_estimators vs max_depth", height=450)\n'
'fig.show()\n'
'\n'
'# 4. Parallel coordinate -- overview of all trials\n'
'fig = optuna.visualization.plot_parallel_coordinate(tpe_study)\n'
'fig.update_layout(title="Parallel Coordinates: All Hyperparameters", height=450)\n'
'fig.show()\n'
'\n'
'# 5. EDF -- how value is distributed across trials\n'
'fig = optuna.visualization.plot_edf(tpe_study)\n'
'fig.update_layout(title="Empirical Distribution of Trial Values", height=400)\n'
'fig.show()'
))

# ── Cell 18: Matplotlib fallback visualization ────────────────────────────────
cells.append(code(
'# Matplotlib fallback: convergence + trial value distribution\n'
'# (useful if Plotly is unavailable or for static export)\n'
'\n'
'values = [t.value for t in tpe_study.trials]\n'
'best_so_far = pd.Series(values).cummax()\n'
'\n'
'fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n'
'\n'
'# Left: convergence\n'
'axes[0].plot(best_so_far.values, color=PALETTE[0], linewidth=2.5, label="Best so far")\n'
'axes[0].scatter(\n'
'    range(len(values)), values,\n'
'    color=PALETTE[0], alpha=0.25, s=15, label="Individual trial"\n'
')\n'
'axes[0].axhline(\n'
'    tpe_study.best_value, color="red", linestyle="--", linewidth=1.5,\n'
'    label=f"Best = {tpe_study.best_value:.4f}"\n'
')\n'
'axes[0].set_title("Optimization History (Matplotlib)", fontweight="bold")\n'
'axes[0].set_xlabel("Trial Number")\n'
'axes[0].set_ylabel("ROC-AUC")\n'
'axes[0].legend()\n'
'\n'
'# Right: distribution of trial values\n'
'axes[1].hist(values, bins=20, color=PALETTE[0], edgecolor="white", alpha=0.85)\n'
'axes[1].axvline(\n'
'    tpe_study.best_value, color="red", linestyle="--", linewidth=2,\n'
'    label=f"Best = {tpe_study.best_value:.4f}"\n'
')\n'
'axes[1].set_title("Distribution of Trial Values", fontweight="bold")\n'
'axes[1].set_xlabel("ROC-AUC")\n'
'axes[1].set_ylabel("Count")\n'
'axes[1].legend()\n'
'\n'
'plt.suptitle("Study Visualization (Matplotlib)", fontsize=14, fontweight="bold")\n'
'plt.tight_layout()\n'
'plt.show()'
))

# ── Cell 19: Section 8 header ─────────────────────────────────────────────────
cells.append(md(
'<a id="8"></a>\n'
'## 8. XGBoost + Optuna: Production Pipeline\n'
'\n'
'Here is a full, competition-ready XGBoost objective covering all major hyperparameters. Key design decisions:\n'
'\n'
'- **StratifiedKFold** ensures balanced class distribution in each fold\n'
'- **Early stopping** per fold prevents overfitting and speeds evaluation\n'
'- **Log-scale** for learning rate, alpha, lambda\n'
'- After optimization: **retrain on full dataset** with best params'
))

# ── Cell 20: XGBoost production code ─────────────────────────────────────────
cells.append(code(
'CV = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n'
'\n'
'\n'
'def xgb_objective(trial):\n'
'    """Production XGBoost objective for Kaggle competitions."""\n'
'    params = {\n'
'        # Boosting params\n'
'        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),\n'
'        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),\n'
'        "max_depth": trial.suggest_int("max_depth", 3, 10),\n'
'        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),\n'
'        # Sampling\n'
'        "subsample": trial.suggest_float("subsample", 0.5, 1.0),\n'
'        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.4, 1.0),\n'
'        "colsample_bylevel": trial.suggest_float("colsample_bylevel", 0.4, 1.0),\n'
'        # Regularization\n'
'        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),\n'
'        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),\n'
'        "gamma": trial.suggest_float("gamma", 0.0, 5.0),\n'
'        # Fixed\n'
'        "eval_metric": "auc",\n'
'        "tree_method": "hist",\n'
'        "random_state": 42,\n'
'        "verbosity": 0,\n'
'        "early_stopping_rounds": 50,\n'
'    }\n'
'\n'
'    oof_scores = []\n'
'    for fold_idx, (train_idx, val_idx) in enumerate(CV.split(X, y)):\n'
'        X_fold_tr, X_fold_val = X[train_idx], X[val_idx]\n'
'        y_fold_tr, y_fold_val = y[train_idx], y[val_idx]\n'
'\n'
'        model = xgb.XGBClassifier(**params)\n'
'        model.fit(\n'
'            X_fold_tr, y_fold_tr,\n'
'            eval_set=[(X_fold_val, y_fold_val)],\n'
'            verbose=False,\n'
'        )\n'
'        preds = model.predict_proba(X_fold_val)[:, 1]\n'
'        oof_scores.append(roc_auc_score(y_fold_val, preds))\n'
'\n'
'    return float(np.mean(oof_scores))\n'
'\n'
'\n'
'xgb_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.TPESampler(seed=42),\n'
'    pruner=optuna.pruners.MedianPruner(n_startup_trials=5),\n'
'    study_name="xgb_production",\n'
')\n'
'xgb_study.optimize(xgb_objective, n_trials=40, show_progress_bar=True)\n'
'\n'
'print(f"\\nXGBoost best CV ROC-AUC: {xgb_study.best_value:.4f}")\n'
'print(f"Best params:")\n'
'for k, v in xgb_study.best_params.items():\n'
'    print(f"  {k}: {v}")'
))

# ── Cell 21: Retrain XGBoost on full data ─────────────────────────────────────
cells.append(code(
'# Retrain best XGBoost on the full dataset\n'
'best_xgb_params = dict(xgb_study.best_params)\n'
'best_xgb_params.update({\n'
'    "eval_metric": "auc",\n'
'    "tree_method": "hist",\n'
'    "random_state": 42,\n'
'    "verbosity": 0,\n'
'})\n'
'# Remove early_stopping_rounds for full retraining (no val set needed)\n'
'best_xgb_params.pop("early_stopping_rounds", None)\n'
'\n'
'best_xgb = xgb.XGBClassifier(**best_xgb_params)\n'
'best_xgb.fit(X, y)\n'
'\n'
'# Feature importance plot\n'
'importances = best_xgb.feature_importances_\n'
'top_n = 15\n'
'top_idx = np.argsort(importances)[-top_n:][::-1]\n'
'\n'
'fig, ax = plt.subplots(figsize=(10, 6))\n'
'bars = ax.barh(\n'
'    [feature_names[i] for i in top_idx][::-1],\n'
'    importances[top_idx][::-1],\n'
'    color=PALETTE[0], edgecolor="white"\n'
')\n'
'ax.set_title(f"Top {top_n} Feature Importances (Tuned XGBoost)", fontweight="bold")\n'
'ax.set_xlabel("Importance Score")\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print(f"Model trained on {X.shape[0]} samples with {X.shape[1]} features.")'
))

# ── Cell 22: Section 9 header ─────────────────────────────────────────────────
cells.append(md(
'<a id="9"></a>\n'
'## 9. LightGBM + Optuna: Production Pipeline\n'
'\n'
'LightGBM has a different set of key hyperparameters compared to XGBoost:\n'
'\n'
'| Parameter | Description | Typical Range |\n'
'|-----------|-------------|---------------|\n'
'| `num_leaves` | Max leaves per tree (complexity) | 20 -- 300 |\n'
'| `min_child_samples` | Min data per leaf (regularization) | 5 -- 100 |\n'
'| `feature_fraction` | Column subsampling ratio | 0.4 -- 1.0 |\n'
'| `bagging_fraction` | Row subsampling ratio | 0.4 -- 1.0 |\n'
'| `bagging_freq` | Bagging frequency | 1 -- 7 |\n'
'| `reg_alpha` | L1 regularization | 1e-8 -- 10 |\n'
'| `reg_lambda` | L2 regularization | 1e-8 -- 10 |\n'
'\n'
'Note: `num_leaves` is more important than `max_depth` in LightGBM because it uses leaf-wise tree growth.'
))

# ── Cell 23: LightGBM production code ────────────────────────────────────────
cells.append(code(
'def lgb_objective(trial):\n'
'    """Production LightGBM objective for Kaggle competitions."""\n'
'    params = {\n'
'        "objective": "binary",\n'
'        "metric": "auc",\n'
'        "verbosity": -1,\n'
'        "boosting_type": "gbdt",\n'
'        "random_state": 42,\n'
'        # Key LGB hyperparameters\n'
'        "num_leaves": trial.suggest_int("num_leaves", 20, 300),\n'
'        "max_depth": trial.suggest_int("max_depth", -1, 12),\n'
'        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),\n'
'        "n_estimators": trial.suggest_int("n_estimators", 100, 1000),\n'
'        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),\n'
'        "feature_fraction": trial.suggest_float("feature_fraction", 0.4, 1.0),\n'
'        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.4, 1.0),\n'
'        "bagging_freq": trial.suggest_int("bagging_freq", 1, 7),\n'
'        "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),\n'
'        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),\n'
'        "path_smooth": trial.suggest_float("path_smooth", 0.0, 1.0),\n'
'    }\n'
'\n'
'    oof_scores = []\n'
'    for fold_idx, (train_idx, val_idx) in enumerate(CV.split(X, y)):\n'
'        X_fold_tr, X_fold_val = X[train_idx], X[val_idx]\n'
'        y_fold_tr, y_fold_val = y[train_idx], y[val_idx]\n'
'\n'
'        train_set = lgb.Dataset(X_fold_tr, label=y_fold_tr)\n'
'        val_set = lgb.Dataset(X_fold_val, label=y_fold_val, reference=train_set)\n'
'\n'
'        callbacks = [\n'
'            lgb.early_stopping(50, verbose=False),\n'
'            lgb.log_evaluation(-1),\n'
'        ]\n'
'        model = lgb.train(\n'
'            params,\n'
'            train_set,\n'
'            num_boost_round=params["n_estimators"],\n'
'            valid_sets=[val_set],\n'
'            callbacks=callbacks,\n'
'        )\n'
'        preds = model.predict(X_fold_val)\n'
'        oof_scores.append(roc_auc_score(y_fold_val, preds))\n'
'\n'
'    return float(np.mean(oof_scores))\n'
'\n'
'\n'
'lgb_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.TPESampler(seed=42),\n'
'    study_name="lgb_production",\n'
')\n'
'lgb_study.optimize(lgb_objective, n_trials=40, show_progress_bar=True)\n'
'\n'
'print(f"\\nLightGBM best CV ROC-AUC: {lgb_study.best_value:.4f}")'
))

# ── Cell 24: XGB vs LGB comparison ───────────────────────────────────────────
cells.append(code(
'# Head-to-head comparison: XGBoost vs LightGBM\n'
'xgb_values = [t.value for t in xgb_study.trials if t.value is not None]\n'
'lgb_values = [t.value for t in lgb_study.trials if t.value is not None]\n'
'\n'
'xgb_best_curve = pd.Series(xgb_values).cummax()\n'
'lgb_best_curve = pd.Series(lgb_values).cummax()\n'
'\n'
'fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n'
'\n'
'# Convergence curves\n'
'axes[0].plot(xgb_best_curve.values, color=PALETTE[0], linewidth=2.5, label="XGBoost")\n'
'axes[0].plot(lgb_best_curve.values, color=PALETTE[1], linewidth=2.5, label="LightGBM")\n'
'axes[0].set_title("XGBoost vs LightGBM Convergence", fontweight="bold")\n'
'axes[0].set_xlabel("Trial Number")\n'
'axes[0].set_ylabel("Best CV ROC-AUC")\n'
'axes[0].legend()\n'
'\n'
'# Boxplots of trial distributions\n'
'data_for_box = [\n'
'    pd.Series(xgb_values, name="XGBoost"),\n'
'    pd.Series(lgb_values, name="LightGBM"),\n'
']\n'
'axes[1].boxplot(\n'
'    [xgb_values, lgb_values],\n'
'    labels=["XGBoost", "LightGBM"],\n'
'    patch_artist=True,\n'
'    boxprops=dict(facecolor=PALETTE[0], alpha=0.6),\n'
'    medianprops=dict(color="red", linewidth=2),\n'
')\n'
'axes[1].set_title("Trial Value Distribution", fontweight="bold")\n'
'axes[1].set_ylabel("CV ROC-AUC")\n'
'\n'
'plt.suptitle("XGBoost vs LightGBM: Optuna-Tuned Comparison", fontsize=14, fontweight="bold")\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print(f"XGBoost  best: {xgb_study.best_value:.4f} (trial #{xgb_study.best_trial.number})")\n'
'print(f"LightGBM best: {lgb_study.best_value:.4f} (trial #{lgb_study.best_trial.number})")'
))

# ── Cell 25: Section 10 header ────────────────────────────────────────────────
cells.append(md(
'<a id="10"></a>\n'
'## 10. Sklearn Integration: OptunaSearchCV\n'
'\n'
'`OptunaSearchCV` is a drop-in replacement for scikit-learn\'s `RandomizedSearchCV` and `GridSearchCV`. It accepts standard sklearn estimators and exposes the familiar `.fit()`, `.best_params_`, and `.best_score_` interface.\n'
'\n'
'**When to use it:**\n'
'- You are already using sklearn pipelines\n'
'- You want Optuna\'s sampling with sklearn\'s cross-validation machinery\n'
'- You need compatibility with sklearn\'s `Pipeline` and `ColumnTransformer`\n'
'\n'
'### Distributions API\n'
'\n'
'Instead of `trial.suggest_*`, `OptunaSearchCV` uses distribution objects:\n'
'\n'
'```python\n'
'from optuna.distributions import (\n'
'    IntDistribution,       # was IntUniformDistribution in older Optuna\n'
'    FloatDistribution,     # was UniformDistribution / LogUniformDistribution\n'
'    CategoricalDistribution,\n'
')\n'
'```'
))

# ── Cell 26: OptunaSearchCV code ──────────────────────────────────────────────
cells.append(code(
'from optuna.integration import OptunaSearchCV\n'
'from optuna.distributions import (\n'
'    IntDistribution,\n'
'    FloatDistribution,\n'
'    CategoricalDistribution,\n'
')\n'
'\n'
'param_distributions = {\n'
'    "n_estimators": IntDistribution(50, 400),\n'
'    "max_depth": IntDistribution(3, 12),\n'
'    "min_samples_split": IntDistribution(2, 30),\n'
'    "min_samples_leaf": IntDistribution(1, 15),\n'
'    "max_features": CategoricalDistribution(["sqrt", "log2"]),\n'
'    "min_impurity_decrease": FloatDistribution(0.0, 0.1),\n'
'}\n'
'\n'
'opt_search = OptunaSearchCV(\n'
'    RandomForestClassifier(random_state=42, n_jobs=-1),\n'
'    param_distributions,\n'
'    n_trials=30,\n'
'    cv=5,\n'
'    scoring="roc_auc",\n'
'    random_state=42,\n'
'    verbose=0,\n'
'    refit=True,  # refit best model on full dataset\n'
')\n'
'opt_search.fit(X, y)\n'
'\n'
'print(f"Best CV ROC-AUC : {opt_search.best_score_:.4f}")\n'
'print(f"\\nBest parameters:")\n'
'for k, v in opt_search.best_params_.items():\n'
'    print(f"  {k}: {v}")\n'
'\n'
'# The underlying study is accessible\n'
'inner_study = opt_search.study_\n'
'print(f"\\nInner study: {len(inner_study.trials)} trials")'
))

# ── Cell 27: Section 11 header ────────────────────────────────────────────────
cells.append(md(
'<a id="11"></a>\n'
'## 11. Multi-Objective Optimization\n'
'\n'
'Real-world ML deployment involves **trade-offs**: you might want high accuracy *and* fast inference, or high AUC *and* low model complexity. Optuna supports multi-objective optimization natively.\n'
'\n'
'### How It Works\n'
'\n'
'- Specify multiple directions: `directions=["maximize", "minimize"]`\n'
'- Optuna finds the **Pareto front** -- the set of trials where no objective can be improved without sacrificing another\n'
'- `study.best_trials` returns all Pareto-optimal trials\n'
'\n'
'### Practical Use Case: AUC vs Training Time\n'
'\n'
'In Kaggle competitions with 9-hour kernels, you may want to find the sweet spot between model quality and compute budget.'
))

# ── Cell 28: Multi-objective code ─────────────────────────────────────────────
cells.append(code(
'def multi_objective(trial):\n'
'    """Optimize AUC (maximize) and training time (minimize) simultaneously."""\n'
'    n_estimators = trial.suggest_int("n_estimators", 10, 300)\n'
'    max_depth = trial.suggest_int("max_depth", 2, 12)\n'
'    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)\n'
'\n'
'    clf = RandomForestClassifier(\n'
'        n_estimators=n_estimators,\n'
'        max_depth=max_depth,\n'
'        min_samples_leaf=min_samples_leaf,\n'
'        random_state=42,\n'
'        n_jobs=-1,\n'
'    )\n'
'    t_start = time.time()\n'
'    auc = cross_val_score(clf, X, y, cv=3, scoring="roc_auc", n_jobs=-1).mean()\n'
'    elapsed = time.time() - t_start\n'
'\n'
'    # Return (AUC, negative_time) -- both maximized\n'
'    return auc, -elapsed\n'
'\n'
'\n'
'mo_study = optuna.create_study(\n'
'    directions=["maximize", "maximize"],\n'
'    study_name="multi_objective",\n'
'    sampler=optuna.samplers.NSGAIISampler(seed=42),\n'
')\n'
'mo_study.optimize(multi_objective, n_trials=50, show_progress_bar=True)\n'
'\n'
'pareto_trials = mo_study.best_trials\n'
'print(f"Total trials  : {len(mo_study.trials)}")\n'
'print(f"Pareto front  : {len(pareto_trials)} trials")\n'
'print(f"\\nSample Pareto-optimal solutions:")\n'
'for t in sorted(pareto_trials, key=lambda t: t.values[0], reverse=True)[:5]:\n'
'    auc_v = t.values[0]\n'
'    time_v = -t.values[1]\n'
'    print(f"  AUC={auc_v:.4f}, time={time_v:.2f}s | {t.params}")'
))

# ── Cell 29: Pareto front visualization ───────────────────────────────────────
cells.append(code(
'# Visualize the Pareto front\n'
'all_aucs = [t.values[0] for t in mo_study.trials if t.values is not None]\n'
'all_times = [-t.values[1] for t in mo_study.trials if t.values is not None]\n'
'pareto_aucs = [t.values[0] for t in pareto_trials]\n'
'pareto_times = [-t.values[1] for t in pareto_trials]\n'
'\n'
'fig, ax = plt.subplots(figsize=(10, 6))\n'
'\n'
'# All trials\n'
'ax.scatter(\n'
'    all_times, all_aucs,\n'
'    color="gray", alpha=0.35, s=25, label="All trials", zorder=2\n'
')\n'
'\n'
'# Pareto front\n'
'pareto_sorted = sorted(zip(pareto_times, pareto_aucs))\n'
'pt_times, pt_aucs = zip(*pareto_sorted)\n'
'ax.scatter(\n'
'    pt_times, pt_aucs,\n'
'    color=PALETTE[1], s=80, zorder=4, label="Pareto front", edgecolors="black"\n'
')\n'
'ax.step(\n'
'    pt_times, pt_aucs,\n'
'    color=PALETTE[1], linewidth=2, where="post", zorder=3\n'
')\n'
'\n'
'ax.set_xlabel("Training Time (seconds)", fontsize=12)\n'
'ax.set_ylabel("CV ROC-AUC", fontsize=12)\n'
'ax.set_title(\n'
'    "Multi-Objective Optimization: AUC vs Training Speed\\n"\n'
'    "(Pareto front = optimal trade-offs)",\n'
'    fontsize=13, fontweight="bold"\n'
')\n'
'ax.legend(fontsize=11)\n'
'plt.tight_layout()\n'
'plt.show()'
))

# ── Cell 30: Section 12 header ────────────────────────────────────────────────
cells.append(md(
'<a id="12"></a>\n'
'## 12. Hyperparameter Importance\n'
'\n'
'Not all hyperparameters matter equally. Optuna\'s `get_param_importances` uses **fANOVA** (functional Analysis of Variance) to measure how much variance in the objective is explained by each hyperparameter.\n'
'\n'
'This is extremely valuable for:\n'
'1. **Focusing future tuning** on the parameters that actually matter\n'
'2. **Reducing search space** by fixing unimportant parameters to reasonable defaults\n'
'3. **Understanding your model** -- which settings drive performance?\n'
'\n'
'Rule of thumb: if a parameter explains < 1% of variance, fix it and save trials.'
))

# ── Cell 31: Hyperparameter importance code ───────────────────────────────────
cells.append(code(
'# fANOVA importance from the TPE study\n'
'importances = optuna.importance.get_param_importances(tpe_study)\n'
'\n'
'print("Hyperparameter Importances (fANOVA):")\n'
'print("-" * 55)\n'
'for param, imp in sorted(importances.items(), key=lambda x: -x[1]):\n'
'    bar = "\u2588" * int(imp * 40)\n'
'    print(f"  {param:30s}: {bar:<40s} {imp:.3f}")\n'
'print("-" * 55)\n'
'\n'
'# Visualize with bar chart\n'
'sorted_params = sorted(importances.items(), key=lambda x: x[1])\n'
'param_names = [p for p, _ in sorted_params]\n'
'imp_values = [v for _, v in sorted_params]\n'
'\n'
'fig, ax = plt.subplots(figsize=(10, 5))\n'
'bars = ax.barh(\n'
'    param_names, imp_values,\n'
'    color=[PALETTE[0] if v > 0.05 else "lightgray" for v in imp_values],\n'
'    edgecolor="white"\n'
')\n'
'ax.axvline(0.05, color="red", linestyle="--", linewidth=1.5,\n'
'           label="5% importance threshold")\n'
'ax.set_title("Hyperparameter Importances (fANOVA)", fontweight="bold", fontsize=13)\n'
'ax.set_xlabel("Relative Importance")\n'
'ax.legend()\n'
'plt.tight_layout()\n'
'plt.show()'
))

# ── Cell 32: Optuna visualization importance ──────────────────────────────────
cells.append(code(
'# Interactive version (Plotly)\n'
'fig = optuna.visualization.plot_param_importances(tpe_study)\n'
'fig.update_layout(\n'
'    title="Hyperparameter Importance (Interactive)",\n'
'    height=400\n'
')\n'
'fig.show()\n'
'\n'
'# LightGBM importance for comparison\n'
'lgb_importances = optuna.importance.get_param_importances(lgb_study)\n'
'print("\\nLightGBM Hyperparameter Importances:")\n'
'print("-" * 55)\n'
'for param, imp in sorted(lgb_importances.items(), key=lambda x: -x[1]):\n'
'    bar = "\u2588" * int(imp * 40)\n'
'    print(f"  {param:30s}: {bar:<40s} {imp:.3f}")'
))

# ── Cell 33: Section 13 header ────────────────────────────────────────────────
cells.append(md(
'<a id="13"></a>\n'
'## 13. Production Tips for Kaggle\n'
'\n'
'### Best Practices at a Glance\n'
'\n'
'| Tip | Why It Matters |\n'
'|-----|----------------|\n'
'| `n_jobs=-1` inside objective | Parallel CV; uses all Kaggle kernel CPUs |\n'
'| `optuna.logging.set_verbosity(WARNING)` | Clean output, no spam |\n'
'| `study.enqueue_trial(params)` | Seed with known-good params from literature |\n'
'| Use `timeout` alongside `n_trials` | Respects the 9-hour kernel limit |\n'
'| Save with `RDBStorage` (SQLite) | Resume study on kernel restart |\n'
'| `log=True` for learning rate | Log scale = equal density per order of magnitude |\n'
'| Set `n_startup_trials` >= 5 in pruner | Avoid pruning during cold start |\n'
'| Use `suggest_float(..., step=0.05)` | Discretize continuous params when needed |\n'
'| Run multiple parallel kernels | Use `storage=` to share the same study |\n'
'| Check `study.trials_dataframe()` | Find clusters of good configurations |\n'
'\n'
'### Advanced: Enqueue Known-Good Trials\n'
'\n'
'If you know from experience or prior work that certain hyperparameter values are good starting points, force Optuna to evaluate them first:\n'
'\n'
'```python\n'
'study.enqueue_trial({\n'
'    "learning_rate": 0.05,\n'
'    "max_depth": 6,\n'
'    "n_estimators": 300,\n'
'    "subsample": 0.8,\n'
'})\n'
'study.optimize(objective, n_trials=100)\n'
'```\n'
'\n'
'### Advanced: Persist Study Across Sessions\n'
'\n'
'```python\n'
'import optuna\n'
'\n'
'storage = optuna.storages.RDBStorage(\n'
'    url="sqlite:///optuna_study.db",\n'
'    engine_kwargs={"connect_args": {"timeout": 10}}\n'
')\n'
'\n'
'study = optuna.create_study(\n'
'    storage=storage,\n'
'    study_name="my_competition_study",\n'
'    direction="maximize",\n'
'    load_if_exists=True,  # Resume if study already exists\n'
')\n'
'```\n'
'\n'
'### Advanced: Distributed Optimization\n'
'\n'
'Run multiple Kaggle kernels sharing the same SQLite/PostgreSQL study:\n'
'\n'
'```python\n'
'# Kernel 1 and Kernel 2 both run this code\n'
'study.optimize(\n'
'    objective,\n'
'    n_trials=100,\n'
'    timeout=3600 * 8,   # 8-hour Kaggle kernel limit\n'
'    n_jobs=1,           # Let storage handle parallelism\n'
')\n'
'```\n'
'\n'
'Optuna handles concurrency automatically -- each kernel will pick up where others left off without duplicating work.'
))

# ── Cell 34: Practical enqueue demo ───────────────────────────────────────────
cells.append(code(
'# Demonstrate enqueue_trial: warm-start with a known-good configuration\n'
'\n'
'warm_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.TPESampler(seed=42),\n'
'    study_name="rf_warmstart",\n'
')\n'
'\n'
'# Enqueue a known-good configuration (e.g., from published paper or prior run)\n'
'warm_study.enqueue_trial({\n'
'    "n_estimators": 200,\n'
'    "max_depth": 8,\n'
'    "min_samples_split": 5,\n'
'    "min_samples_leaf": 2,\n'
'    "max_features": "sqrt",\n'
'})\n'
'\n'
'warm_study.optimize(objective, n_trials=40, show_progress_bar=False)\n'
'\n'
'print(f"Warm-start study best: {warm_study.best_value:.4f}")\n'
'\n'
'# Trial 0 should be our enqueued configuration\n'
'trial_0 = warm_study.trials[0]\n'
'print(f"\\nTrial 0 (enqueued): score={trial_0.value:.4f}, params={trial_0.params}")\n'
'\n'
'# Compare warm vs cold start convergence\n'
'warm_vals = pd.Series([t.value for t in warm_study.trials]).cummax()\n'
'cold_vals = pd.Series([t.value for t in tpe_study.trials]).cummax()\n'
'\n'
'fig, ax = plt.subplots(figsize=(10, 5))\n'
'ax.plot(cold_vals.values[:40], color=PALETTE[0], linewidth=2.5, label="Cold start (TPE)")\n'
'ax.plot(warm_vals.values[:40], color=PALETTE[1], linewidth=2.5, label="Warm start (enqueue)")\n'
'ax.set_title("Cold Start vs Warm Start Convergence", fontweight="bold", fontsize=13)\n'
'ax.set_xlabel("Trial Number")\n'
'ax.set_ylabel("Best ROC-AUC")\n'
'ax.legend()\n'
'plt.tight_layout()\n'
'plt.show()'
))

# ── Cell 35: Timeout demo ─────────────────────────────────────────────────────
cells.append(code(
'# Demonstrate timeout: run for at most 30 seconds\n'
'timeout_study = optuna.create_study(\n'
'    direction="maximize",\n'
'    sampler=optuna.samplers.TPESampler(seed=42),\n'
')\n'
'\n'
't_start = time.time()\n'
'timeout_study.optimize(\n'
'    objective,\n'
'    n_trials=10000,    # large upper bound\n'
'    timeout=30,        # but stop after 30 seconds\n'
'    show_progress_bar=False,\n'
')\n'
'elapsed = time.time() - t_start\n'
'\n'
'print(f"Completed {len(timeout_study.trials)} trials in {elapsed:.1f}s (timeout=30s)")\n'
'print(f"Best value: {timeout_study.best_value:.4f}")\n'
'print(f"\\nIn a 9-hour Kaggle kernel, set timeout=32400 (= 9 * 3600)")'
))

# ── Cell 36: Closing markdown ─────────────────────────────────────────────────
cells.append(md(
'---\n'
'\n'
'## Key Takeaways\n'
'\n'
'| Topic | What You Learned |\n'
'|-------|------------------|\n'
'| **TPE Sampler** | Bayesian optimization via density ratio; best general-purpose choice |\n'
'| **CMA-ES** | Evolution strategy for high-dim continuous spaces |\n'
'| **Pruning** | Kill bad trials early; 30-70% speedup with MedianPruner |\n'
'| **Visualization** | Interactive Plotly plots; matplotlib fallbacks |\n'
'| **XGBoost / LGB** | Full production objectives with StratifiedKFold + early stopping |\n'
'| **OptunaSearchCV** | Drop-in sklearn API; compatible with Pipelines |\n'
'| **Multi-Objective** | Pareto front; trade-off AUC vs speed/complexity |\n'
'| **Importance** | fANOVA tells you which params matter -- focus your budget there |\n'
'| **Production Tips** | Enqueue seeds, timeout, RDBStorage, distributed kernels |\n'
'\n'
'### Recommended Optuna Workflow for Kaggle\n'
'\n'
'```\n'
'1. Quick scan: 30 trials, wide bounds, RandomSampler  -> understand the space\n'
'2. Focused run: 100 trials, TPE, narrowed bounds      -> exploit promising regions\n'
'3. Importance check: fANOVA -> fix low-importance params\n'
'4. Final run: 200 trials, TPE, tight bounds, pruning  -> squeeze out final gains\n'
'5. Retrain best params on full train set              -> submit\n'
'```\n'
'\n'
'### Further Reading\n'
'\n'
'- [Optuna Official Documentation](https://optuna.readthedocs.io/)\n'
'- [Bergstra & Bengio (2012): Random Search for Hyper-Parameter Optimization](https://jmlr.org/papers/v13/bergstra12a.html)\n'
'- [Bergstra et al. (2011): Algorithms for Hyper-Parameter Optimization (TPE)](https://proceedings.neurips.cc/paper/2011/hash/86e8f7ab32cfd12577bc2619bc635690-Abstract.html)\n'
'- [Hansen (2016): The CMA Evolution Strategy](https://arxiv.org/abs/1604.00772)\n'
'- [Hutter et al. (2014): An Efficient Approach for Assessing Hyperparameter Importance (fANOVA)](http://proceedings.mlr.press/v32/hutter14.html)\n'
'\n'
'---\n'
'\n'
'### Portfolio Quality Addendum\n'
'\n'
'This notebook is part of a systematic Kaggle Grandmaster portfolio covering:\n'
'\n'
'- Feature Engineering Cookbook (50 techniques)\n'
'- Ensemble & Stacking Guide\n'
'- LLM Fine-tuning Cookbook (LoRA / QLoRA)\n'
'- Attention Mechanisms Walkthrough\n'
'- RAG from Scratch\n'
'- Graph Neural Networks\n'
'- **Optuna Hyperparameter Optimization Guide (this notebook)**\n'
'\n'
'---\n'
'\n'
'**If this notebook helped you, please upvote!** Feedback and comments are very welcome.\n'
'\n'
'*Lorenzo Scaturchio | February 2026*'
))

# ── Notebook assembly ─────────────────────────────────────────────────────────

write_notebook(cells, __file__, "optuna_hyperparameter_guide.ipynb")
