#!/usr/bin/env python3
"""Build the shap_explainability_guide.ipynb notebook."""
import sys as _sys
import os as _os


def _find_repo_root(start_dir):
    current = _os.path.abspath(start_dir)
    while True:
        if _os.path.exists(_os.path.join(current, "manage.sh")) and _os.path.isdir(_os.path.join(current, "kaggle_portfolio")):
            return current
        parent = _os.path.dirname(current)
        if parent == current:
            return _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
        current = parent


_sys.path.insert(0, _find_repo_root(_os.path.dirname(_os.path.abspath(__file__))))
from kaggle_portfolio.shared.build_utils import md, code, write_notebook

cells = []

# ── Cell 1: Title Banner ──────────────────────────────────────────────────────
cells.append(md(
'# <center>SHAP: Model Explainability Masterclass</center>\n'
'\n'
'<center>\n'
'\n'
'![Python](https://img.shields.io/badge/Python-3.10-blue?logo=python&logoColor=white)\n'
'![SHAP](https://img.shields.io/badge/SHAP-0.44-orange)\n'
'![XGBoost](https://img.shields.io/badge/XGBoost-2.0-green)\n'
'![scikit-learn](https://img.shields.io/badge/scikit--learn-1.3-orange?logo=scikit-learn)\n'
'![License](https://img.shields.io/badge/License-MIT-red)\n'
'\n'
'</center>\n'
'\n'
'---\n'
'\n'
'**Author:** Lorenzo Scaturchio  \n'
'**Last Updated:** February 2026  \n'
'**Kernel Version:** 1.0\n'
'\n'
'> *"A model that cannot be explained cannot be trusted in production."*\n'
'\n'
'---\n'
'\n'
'This notebook is a **complete, practical guide** to SHAP (SHapley Additive exPlanations) -- '
'the gold standard for model explainability in machine learning. Whether you are debugging a '
'model, explaining predictions to stakeholders, or satisfying regulatory requirements, SHAP '
'gives you principled, consistent, locally-accurate feature attributions grounded in game theory.\n'
'\n'
'If you find this notebook useful, please consider giving it an **upvote** -- it helps others discover it!'
))

# ── Cell 2: TL;DR ─────────────────────────────────────────────────────────────
cells.append(md(
'## TL;DR\n'
'\n'
'| Section | What You Will Learn |\n'
'|---------|---------------------|\n'
'| **1. What is SHAP?** | Game theory foundations, Shapley values, why SHAP beats naive feature importance |\n'
'| **2. Setup & Dataset** | Installation, California Housing dataset, train/test split |\n'
'| **3. TreeExplainer** | Fast exact SHAP for XGBoost, LightGBM, Random Forest |\n'
'| **4. Summary Plots** | Beeswarm and bar charts for global feature importance |\n'
'| **5. Force Plots** | Single-prediction and multi-sample interactive explanation |\n'
'| **6. Waterfall Plots** | Step-by-step contribution breakdown per prediction |\n'
'| **7. Dependence Plots** | Non-linear effects and interaction detection |\n'
'| **8. Interaction Values** | Pairwise SHAP interaction matrix |\n'
'| **9. LinearExplainer** | SHAP for linear models, comparison to coefficients |\n'
'| **10. KernelExplainer** | Model-agnostic SHAP for any black-box model |\n'
'| **11. Classification** | Binary and multi-class SHAP value handling |\n'
'| **12. Best Practices** | Production tips, performance, pitfalls |\n'
))

# ── Cell 3: Table of Contents ─────────────────────────────────────────────────
cells.append(md(
'## Table of Contents\n'
'\n'
'1. [What is SHAP?](#1-what-is-shap)\n'
'2. [Setup & Dataset](#2-setup--dataset)\n'
'3. [TreeExplainer](#3-treeexplainer)\n'
'4. [Summary Plots](#4-summary-plots)\n'
'5. [Force Plots](#5-force-plots)\n'
'6. [Waterfall Plots](#6-waterfall-plots)\n'
'7. [Dependence Plots](#7-dependence-plots)\n'
'8. [SHAP Interaction Values](#8-shap-interaction-values)\n'
'9. [LinearExplainer](#9-linearexplainer)\n'
'10. [KernelExplainer (model-agnostic)](#10-kernelexplainer-model-agnostic)\n'
'11. [SHAP for Classification](#11-shap-for-classification)\n'
'12. [Production Tips & Best Practices](#12-production-tips--best-practices)\n'
))

# ── Cell 4: Section 1 - What is SHAP? (markdown) ──────────────────────────────
cells.append(md(
'---\n'
'## 1. What is SHAP?\n'
'\n'
'### Game Theory Foundations\n'
'\n'
'SHAP is rooted in **cooperative game theory**. Imagine your model\'s features as players in a '
'coalition game: together they "earn" a prediction (the payout). The question is: how do we '
'fairly credit each player for their contribution?\n'
'\n'
'Lloyd Shapley (Nobel Prize 2012) solved this in 1951. The **Shapley value** of player $i$ is '
'the average marginal contribution of feature $i$ across all possible orderings of features:\n'
'\n'
'$$\\phi_i = \\sum_{S \\subseteq F \\setminus \\{i\\}} \\frac{|S|!(|F|-|S|-1)!}{|F|!} '
'\\left[ f(S \\cup \\{i\\}) - f(S) \\right]$$\n'
'\n'
'Where:\n'
'- $F$ = full set of features\n'
'- $S$ = subset of features not containing $i$\n'
'- $f(S)$ = model output using only features in $S$\n'
'\n'
'### SHAP = SHapley Additive exPlanations\n'
'\n'
'Lundberg & Lee (2017) showed that Shapley values are the **unique** attribution method satisfying '
'three desirable axioms simultaneously:\n'
'\n'
'| Axiom | Meaning |\n'
'|-------|--------|\n'
'| **Local Accuracy** | SHAP values sum exactly to the prediction minus the base value |\n'
'| **Missingness** | Features absent from a sample have zero SHAP value |\n'
'| **Consistency** | If a feature\'s contribution increases in a changed model, its SHAP value does not decrease |\n'
'\n'
'The additive explanation model is:\n'
'\n'
'$$\\hat{f}(x) = \\phi_0 + \\sum_{i=1}^{M} \\phi_i x_i\'$$\n'
'\n'
'Where $\\phi_0 = E[f(x)]$ (the base value / expected model output) and $\\phi_i$ is the SHAP '
'value for feature $i$.\n'
'\n'
'### Why SHAP Beats Naive Feature Importance\n'
'\n'
'| Method | Local? | Consistent? | Handles Correlations? | Speed |\n'
'|--------|--------|-------------|----------------------|-------|\n'
'| Permutation Importance | No (global only) | No | No | Medium |\n'
'| Gain / Impurity Importance | No | No | No | Fast |\n'
'| LIME | Yes | No | Partial | Slow |\n'
'| **SHAP** | **Yes** | **Yes** | **Yes** | **Fast (trees)** |\n'
'\n'
'Standard tree-based feature importance can be misleading for correlated features and gives '
'no information about individual predictions. SHAP provides both local (per-prediction) and '
'global (aggregated) explanations with theoretical guarantees.'
))

# ── Cell 5: Section 2 - Setup & Dataset (markdown) ────────────────────────────
cells.append(md(
'---\n'
'## 2. Setup & Dataset\n'
'\n'
'We use the **California Housing** dataset from scikit-learn -- no external data download needed. '
'It contains 20,640 census block groups with 8 features predicting median house value.\n'
'\n'
'| Feature | Description |\n'
'|---------|------------|\n'
'| `MedInc` | Median income in block group |\n'
'| `HouseAge` | Median house age in block group |\n'
'| `AveRooms` | Average number of rooms per household |\n'
'| `AveBedrms` | Average number of bedrooms per household |\n'
'| `Population` | Block group population |\n'
'| `AveOccup` | Average number of household members |\n'
'| `Latitude` | Block group latitude |\n'
'| `Longitude` | Block group longitude |\n'
'\n'
'**Target:** Median house value (in $100,000s)'
))

# ── Cell 6: Setup & Imports (code) ────────────────────────────────────────────
cells.append(code(
'!pip install shap xgboost lightgbm -q'
))

cells.append(code(
'import shap\n'
'import numpy as np\n'
'import pandas as pd\n'
'import matplotlib.pyplot as plt\n'
'import seaborn as sns\n'
'from sklearn.datasets import fetch_california_housing, make_classification\n'
'from sklearn.model_selection import train_test_split\n'
'from sklearn.ensemble import RandomForestRegressor, GradientBoostingClassifier\n'
'from sklearn.linear_model import LinearRegression, LogisticRegression\n'
'from sklearn.preprocessing import StandardScaler\n'
'from sklearn.pipeline import Pipeline\n'
'import xgboost as xgb\n'
'import lightgbm as lgb\n'
'import warnings\n'
'warnings.filterwarnings(\'ignore\')\n'
'\n'
'# Matplotlib inline display\n'
'%matplotlib inline\n'
'plt.rcParams[\'figure.dpi\'] = 120\n'
'plt.rcParams[\'figure.figsize\'] = (10, 6)\n'
'\n'
'print(f"SHAP version: {shap.__version__}")\n'
'print(f"XGBoost version: {xgb.__version__}")\n'
'print(f"LightGBM version: {lgb.__version__}")'
))

cells.append(code(
'# Load California Housing dataset\n'
'housing = fetch_california_housing(as_frame=True)\n'
'X_raw = housing.data\n'
'y_raw = housing.target\n'
'\n'
'X_train, X_test, y_train, y_test = train_test_split(\n'
'    X_raw, y_raw, test_size=0.2, random_state=42\n'
')\n'
'\n'
'print(f"Dataset shape: {X_raw.shape}")\n'
'print(f"Training set: {X_train.shape}, Test set: {X_test.shape}")\n'
'print(f"Target range: [{y_raw.min():.2f}, {y_raw.max():.2f}] ($100k units)")\n'
'print()\n'
'print("Feature overview:")\n'
'X_raw.describe().round(2)'
))

# ── Cell 9: Section 3 - TreeExplainer (markdown) ──────────────────────────────
cells.append(md(
'---\n'
'## 3. TreeExplainer\n'
'\n'
'`shap.TreeExplainer` is the **fastest and most accurate** SHAP implementation. It exploits '
'the tree structure to compute exact Shapley values in polynomial time (instead of exponential). '
'It works with:\n'
'- XGBoost\n'
'- LightGBM\n'
'- CatBoost\n'
'- scikit-learn RandomForest, ExtraTrees, GradientBoosting, DecisionTree\n'
'\n'
'### Key Objects\n'
'\n'
'| Object | Description |\n'
'|--------|------------|\n'
'| `explainer.expected_value` | Base value $\\phi_0 = E[f(x)]$ -- mean prediction over training set |\n'
'| `shap_values.values` | Matrix of shape `(n_samples, n_features)` -- the SHAP values |\n'
'| `shap_values.base_values` | Per-sample base value (same as `expected_value` for regression) |\n'
'| `shap_values.data` | Original feature values used for explanation |\n'
'\n'
'### Local Accuracy Check\n'
'\n'
'For any sample $x$: `base_value + sum(shap_values[x]) == model.predict(x)` (up to floating point).'
))

cells.append(code(
'# Train XGBoost regressor\n'
'xgb_model = xgb.XGBRegressor(\n'
'    n_estimators=200,\n'
'    max_depth=5,\n'
'    learning_rate=0.1,\n'
'    subsample=0.8,\n'
'    colsample_bytree=0.8,\n'
'    random_state=42,\n'
'    n_jobs=-1\n'
')\n'
'xgb_model.fit(X_train, y_train)\n'
'\n'
'from sklearn.metrics import mean_squared_error, r2_score\n'
'y_pred = xgb_model.predict(X_test)\n'
'rmse = np.sqrt(mean_squared_error(y_test, y_pred))\n'
'r2 = r2_score(y_test, y_pred)\n'
'print(f"XGBoost RMSE: {rmse:.4f}")\n'
'print(f"XGBoost R2:   {r2:.4f}")'
))

cells.append(code(
'# Create TreeExplainer and compute SHAP values\n'
'explainer = shap.TreeExplainer(xgb_model)\n'
'\n'
'# Compute SHAP values for first 1000 test samples (returns Explanation object)\n'
'shap_values = explainer(X_test.iloc[:1000])\n'
'\n'
'print(f"Expected value (base value): {explainer.expected_value:.4f}")\n'
'print(f"SHAP values shape: {shap_values.values.shape}")\n'
'print(f"  -> (n_samples={shap_values.values.shape[0]}, n_features={shap_values.values.shape[1]})")\n'
'\n'
'# Local accuracy verification\n'
'sample_idx = 42\n'
'base_val = explainer.expected_value\n'
'shap_sum = shap_values.values[sample_idx].sum()\n'
'model_pred = xgb_model.predict(X_test.iloc[[sample_idx]])[0]\n'
'\n'
'print(f"\\n--- Local Accuracy Check (sample {sample_idx}) ---")\n'
'print(f"Base value:              {base_val:.6f}")\n'
'print(f"Sum of SHAP values:      {shap_sum:.6f}")\n'
'print(f"Base + SHAP sum:         {base_val + shap_sum:.6f}")\n'
'print(f"Model prediction:        {model_pred:.6f}")\n'
'print(f"Match: {np.isclose(base_val + shap_sum, model_pred, atol=1e-4)}")'
))

# ── Cell 13: Section 4 - Summary Plots (markdown) ─────────────────────────────
cells.append(md(
'---\n'
'## 4. Summary Plots\n'
'\n'
'Summary plots aggregate SHAP values across many samples to give a **global view** of feature importance.\n'
'\n'
'### Beeswarm Plot (default)\n'
'- Each dot is one sample\n'
'- X-axis: SHAP value (positive = pushes prediction up, negative = pushes down)\n'
'- Color: feature value (red = high, blue = low)\n'
'- Vertical spread shows density of samples at each SHAP value\n'
'- Features are sorted by mean |SHAP| (most important at top)\n'
'\n'
'### Bar Chart\n'
'- Shows mean |SHAP| value per feature\n'
'- Good for a clean summary for stakeholders\n'
'- Loses information about direction of effect'
))

cells.append(code(
'# Beeswarm summary plot (default)\n'
'plt.figure()\n'
'shap.summary_plot(shap_values, X_test.iloc[:1000], show=False)\n'
'plt.title("SHAP Summary Plot (Beeswarm) -- California Housing", fontsize=14, pad=15)\n'
'plt.tight_layout()\n'
'plt.show()'
))

cells.append(code(
'# Bar chart summary plot\n'
'plt.figure()\n'
'shap.summary_plot(shap_values, X_test.iloc[:1000], plot_type="bar", show=False)\n'
'plt.title("SHAP Feature Importance (Mean |SHAP|) -- California Housing", fontsize=14, pad=15)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'# Print ranked feature importances\n'
'mean_abs_shap = pd.Series(\n'
'    np.abs(shap_values.values).mean(axis=0),\n'
'    index=X_test.columns\n'
').sort_values(ascending=False)\n'
'\n'
'print("\\nRanked Feature Importances (Mean |SHAP|):")\n'
'for rank, (feat, val) in enumerate(mean_abs_shap.items(), 1):\n'
'    bar = "=" * int(val / mean_abs_shap.max() * 30)\n'
'    print(f"  {rank}. {feat:<12} {val:.4f}  |{bar}")'
))

# ── Cell 16: Section 5 - Force Plots (markdown) ───────────────────────────────
cells.append(md(
'---\n'
'## 5. Force Plots\n'
'\n'
'A force plot shows **how each feature pushes the prediction** away from the base value for a '
'single sample (or a batch of samples).\n'
'\n'
'### How to Read a Force Plot\n'
'- The **base value** ($\\phi_0$) is where the arrow starts -- it is the average model output\n'
'- **Red arrows** push the prediction **higher** (positive SHAP values)\n'
'- **Blue arrows** push the prediction **lower** (negative SHAP values)\n'
'- The final **output value** is where the arrows land\n'
'- Arrow **width** is proportional to |SHAP value|\n'
'\n'
'For multi-sample force plots, samples are stacked vertically and ordered by a clustering '
'algorithm, revealing groups of similar explanations.'
))

cells.append(code(
'# Single prediction force plot\n'
'sample_idx = 0\n'
'print(f"Prediction for sample {sample_idx}: {xgb_model.predict(X_test.iloc[[sample_idx]])[0]:.4f}")\n'
'print(f"Base value: {explainer.expected_value:.4f}")\n'
'print()\n'
'\n'
'# Display force plot inline\n'
'shap.initjs()\n'
'force_plot = shap.force_plot(\n'
'    explainer.expected_value,\n'
'    shap_values.values[sample_idx],\n'
'    X_test.iloc[sample_idx],\n'
'    matplotlib=True,\n'
'    show=False\n'
')\n'
'plt.title(f"Force Plot -- Sample {sample_idx}", fontsize=12, pad=20)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'# Print top contributors for this sample\n'
'sample_shap = pd.Series(\n'
'    shap_values.values[sample_idx],\n'
'    index=X_test.columns\n'
').sort_values(key=abs, ascending=False)\n'
'print("Top SHAP contributors:")\n'
'for feat, val in sample_shap.items():\n'
'    direction = "UP  " if val > 0 else "DOWN"\n'
'    print(f"  {direction} | {feat:<12} {val:+.4f}")'
))

cells.append(code(
'# Matplotlib-rendered force plots for multiple samples (stacked)\n'
'n_samples_force = 50\n'
'\n'
'plt.figure(figsize=(14, 5))\n'
'shap.force_plot(\n'
'    explainer.expected_value,\n'
'    shap_values.values[:n_samples_force],\n'
'    X_test.iloc[:n_samples_force],\n'
'    matplotlib=True,\n'
'    show=False\n'
')\n'
'plt.title(f"Force Plot -- First {n_samples_force} Test Samples", fontsize=12)\n'
'plt.tight_layout()\n'
'plt.show()'
))

# ── Cell 19: Section 6 - Waterfall Plots (markdown) ───────────────────────────
cells.append(md(
'---\n'
'## 6. Waterfall Plots\n'
'\n'
'Waterfall plots are similar to force plots but presented as a **vertical bar chart**, making '
'it easier to read exact SHAP values and trace the exact path from base value to prediction.\n'
'\n'
'### Waterfall vs Force Plot\n'
'\n'
'| Aspect | Force Plot | Waterfall Plot |\n'
'|--------|-----------|----------------|\n'
'| Layout | Horizontal arrows | Vertical bars |\n'
'| Values | Proportional width | Exact numbers shown |\n'
'| Best for | Visual intuition | Detailed analysis |\n'
'| Multi-sample | Yes (stacked) | No (one at a time) |\n'
'\n'
'The waterfall plot shows features ordered by |SHAP value|, with the cumulative sum '
'tracing from $E[f(x)]$ (bottom) to $f(x)$ (top).'
))

cells.append(code(
'# Waterfall plot for a single prediction\n'
'sample_idx = 0\n'
'shap.waterfall_plot(shap_values[sample_idx], show=False)\n'
'plt.title(f"SHAP Waterfall Plot -- Sample {sample_idx}", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()'
))

cells.append(code(
'# Compare waterfall plots for two different predictions\n'
'# Find a high-value and low-value prediction in the test set\n'
'preds = xgb_model.predict(X_test.iloc[:1000])\n'
'high_idx = int(np.argmax(preds))\n'
'low_idx = int(np.argmin(preds))\n'
'\n'
'fig, axes = plt.subplots(1, 2, figsize=(18, 7))\n'
'\n'
'plt.sca(axes[0])\n'
'shap.waterfall_plot(shap_values[high_idx], show=False)\n'
'axes[0].set_title(f"High Prediction ({preds[high_idx]:.2f}) -- Sample {high_idx}", fontsize=11)\n'
'\n'
'plt.sca(axes[1])\n'
'shap.waterfall_plot(shap_values[low_idx], show=False)\n'
'axes[1].set_title(f"Low Prediction ({preds[low_idx]:.2f}) -- Sample {low_idx}", fontsize=11)\n'
'\n'
'plt.suptitle("Waterfall Plot Comparison: High vs Low Prediction", fontsize=13, y=1.01)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print(f"High prediction: {preds[high_idx]:.4f} (mean: {preds.mean():.4f})")\n'
'print(f"Low  prediction: {preds[low_idx]:.4f}")'
))

# ── Cell 22: Section 7 - Dependence Plots (markdown) ──────────────────────────
cells.append(md(
'---\n'
'## 7. Dependence Plots\n'
'\n'
'Dependence plots show the relationship between **a feature\'s value** and its **SHAP value**, '
'revealing how the model uses that feature across the dataset.\n'
'\n'
'### How to Read a Dependence Plot\n'
'- **X-axis:** Feature value\n'
'- **Y-axis:** SHAP value for that feature\n'
'- **Color:** Value of an automatically selected interaction feature\n'
'- Non-linearity in the scatter = non-linear effect captured by the model\n'
'- Vertical spread at a given X value = interaction with other features\n'
'\n'
'### Interaction Detection\n'
'\n'
'SHAP auto-selects the color feature that best explains residual vertical spread. '
'You can also specify the interaction feature manually with `interaction_index`.'
))

cells.append(code(
'# Dependence plot for MedInc (most important feature)\n'
'plt.figure(figsize=(10, 6))\n'
'shap.dependence_plot(\n'
'    "MedInc",\n'
'    shap_values.values,\n'
'    X_test.iloc[:1000],\n'
'    show=False\n'
')\n'
'plt.title("SHAP Dependence Plot: MedInc (auto interaction)", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()'
))

cells.append(code(
'# Dependence plots for top 4 features in a 2x2 grid\n'
'top_features = mean_abs_shap.index[:4].tolist()\n'
'\n'
'fig, axes = plt.subplots(2, 2, figsize=(16, 12))\n'
'axes = axes.flatten()\n'
'\n'
'for ax, feat in zip(axes, top_features):\n'
'    plt.sca(ax)\n'
'    shap.dependence_plot(\n'
'        feat,\n'
'        shap_values.values,\n'
'        X_test.iloc[:1000],\n'
'        ax=ax,\n'
'        show=False\n'
'    )\n'
'    ax.set_title(f"SHAP Dependence: {feat}", fontsize=11)\n'
'\n'
'plt.suptitle("Dependence Plots -- Top 4 Features", fontsize=14, y=1.01)\n'
'plt.tight_layout()\n'
'plt.show()'
))

cells.append(code(
'# Custom interaction: MedInc vs AveRooms\n'
'plt.figure(figsize=(10, 6))\n'
'shap.dependence_plot(\n'
'    "MedInc",\n'
'    shap_values.values,\n'
'    X_test.iloc[:1000],\n'
'    interaction_index="AveRooms",\n'
'    show=False\n'
')\n'
'plt.title("SHAP Dependence: MedInc (colored by AveRooms)", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print("Interpretation:")\n'
'print("  - The curve shape reveals how MedInc effect is captured by the model")\n'
'print("  - Color (AveRooms) shows if the MedInc effect differs by number of rooms")\n'
'print("  - Vertical spread at same MedInc = interaction with AveRooms")'
))

# ── Cell 26: Section 8 - Interaction Values (markdown) ────────────────────────
cells.append(md(
'---\n'
'## 8. SHAP Interaction Values\n'
'\n'
'SHAP interaction values decompose the SHAP values into **main effects** and **pairwise '
'interaction effects**:\n'
'\n'
'$$\\phi_{i,j}(f, x) = \\text{interaction SHAP value of feature } i \\text{ with feature } j$$\n'
'\n'
'The diagonal ($i = j$) gives the main effect; off-diagonal gives interaction effects.\n'
'\n'
'**Note:** Computing interaction values requires `shap_interaction_values()` which is '
'**O(n_features^2)** more expensive than regular SHAP values. Use with a small sample '
'(< 500 rows) to avoid memory issues.\n'
'\n'
'The interaction heatmap below shows which feature pairs have the strongest interactions. '
'Darker colors = stronger interaction.'
))

cells.append(code(
'# Compute SHAP interaction values (memory-intensive -- use small sample)\n'
'n_interaction_samples = 200\n'
'X_interaction = X_test.iloc[:n_interaction_samples]\n'
'\n'
'print(f"Computing SHAP interaction values for {n_interaction_samples} samples...")\n'
'print("This is O(n_features^2) more expensive -- using a small sample.")\n'
'\n'
'# Use legacy shap_interaction_values for the matrix\n'
'shap_interaction = explainer.shap_interaction_values(X_interaction)\n'
'\n'
'print(f"Interaction values shape: {shap_interaction.shape}")\n'
'print(f"  -> (n_samples, n_features, n_features) = {shap_interaction.shape}")\n'
'\n'
'# Mean absolute interaction matrix\n'
'mean_interaction = np.abs(shap_interaction).mean(axis=0)\n'
'\n'
'# Plot interaction heatmap\n'
'fig, ax = plt.subplots(figsize=(9, 7))\n'
'mask = np.zeros_like(mean_interaction, dtype=bool)\n'
'np.fill_diagonal(mask, True)  # Hide main effects (diagonal) for clarity\n'
'\n'
'sns.heatmap(\n'
'    pd.DataFrame(mean_interaction, index=X_test.columns, columns=X_test.columns),\n'
'    annot=True, fmt=".3f",\n'
'    cmap="YlOrRd",\n'
'    ax=ax,\n'
'    linewidths=0.5,\n'
'    cbar_kws={"label": "Mean |SHAP Interaction Value|"}\n'
')\n'
'ax.set_title("SHAP Pairwise Interaction Values\\n(Off-diagonal = interaction, Diagonal = main effect)", fontsize=12)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'# Top interactions\n'
'interactions = []\n'
'n_feats = len(X_test.columns)\n'
'for i in range(n_feats):\n'
'    for j in range(i + 1, n_feats):\n'
'        interactions.append({\n'
'            "feature_1": X_test.columns[i],\n'
'            "feature_2": X_test.columns[j],\n'
'            "mean_abs_interaction": mean_interaction[i, j]\n'
'        })\n'
'\n'
'top_interactions = pd.DataFrame(interactions).sort_values("mean_abs_interaction", ascending=False)\n'
'print("\\nTop 5 Feature Interactions:")\n'
'print(top_interactions.head(5).to_string(index=False))'
))

# ── Cell 28: Section 9 - LinearExplainer (markdown) ───────────────────────────
cells.append(md(
'---\n'
'## 9. LinearExplainer\n'
'\n'
'`shap.LinearExplainer` computes **exact SHAP values** for linear models analytically. '
'It is much faster than KernelExplainer and handles feature correlations correctly '
'by using the covariance matrix of the training data.\n'
'\n'
'### When to Use LinearExplainer\n'
'- Model is `LinearRegression`, `LogisticRegression`, `Ridge`, `Lasso`, `ElasticNet`, `SGDClassifier`, etc.\n'
'- You want to compare SHAP values to model coefficients\n'
'- You need interpretability for a simple, auditable model\n'
'\n'
'### SHAP vs Coefficients\n'
'\n'
'Linear model coefficients measure the **marginal effect** of a feature holding others constant. '
'SHAP values measure the **actual contribution** for a specific sample, accounting for the '
'actual feature values. For a linear model:\n'
'\n'
'$$\\phi_i(x) \\approx \\beta_i \\cdot (x_i - E[x_i])$$\n'
'\n'
'(Exact when features are independent; LinearExplainer adjusts for correlations.)'
))

cells.append(code(
'# Train Linear Regression\n'
'lr_model = LinearRegression()\n'
'lr_model.fit(X_train, y_train)\n'
'\n'
'y_pred_lr = lr_model.predict(X_test)\n'
'rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))\n'
'r2_lr = r2_score(y_test, y_pred_lr)\n'
'print(f"LinearRegression RMSE: {rmse_lr:.4f}")\n'
'print(f"LinearRegression R2:   {r2_lr:.4f}")\n'
'\n'
'# Create LinearExplainer\n'
'explainer_lr = shap.LinearExplainer(\n'
'    lr_model,\n'
'    X_train,\n'
'    feature_perturbation="correlation_dependent"  # accounts for correlations\n'
')\n'
'\n'
'shap_values_lr = explainer_lr(X_test.iloc[:1000])\n'
'\n'
'print(f"\\nLinear SHAP values shape: {shap_values_lr.values.shape}")\n'
'print(f"Expected value (linear): {explainer_lr.expected_value:.4f}")\n'
'print(f"Training mean target:    {y_train.mean():.4f}")'
))

cells.append(code(
'# Compare SHAP values to model coefficients\n'
'coef_df = pd.DataFrame({\n'
'    "feature": X_train.columns,\n'
'    "coefficient": lr_model.coef_,\n'
'    "mean_shap": shap_values_lr.values.mean(axis=0),\n'
'    "mean_abs_shap": np.abs(shap_values_lr.values).mean(axis=0)\n'
'}).sort_values("mean_abs_shap", ascending=False)\n'
'\n'
'print("Linear Model: Coefficients vs Mean SHAP Values")\n'
'print("=" * 65)\n'
'print(coef_df.to_string(index=False, float_format=lambda x: f"{x:+.4f}"))\n'
'\n'
'# Side-by-side bar plot\n'
'fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n'
'\n'
'coef_sorted = coef_df.sort_values("coefficient")\n'
'colors_coef = ["#e74c3c" if c > 0 else "#3498db" for c in coef_sorted["coefficient"]]\n'
'axes[0].barh(coef_sorted["feature"], coef_sorted["coefficient"], color=colors_coef)\n'
'axes[0].axvline(0, color="black", linewidth=0.8)\n'
'axes[0].set_title("Linear Regression Coefficients", fontsize=12)\n'
'axes[0].set_xlabel("Coefficient Value")\n'
'\n'
'shap_sorted = coef_df.sort_values("mean_shap")\n'
'colors_shap = ["#e74c3c" if v > 0 else "#3498db" for v in shap_sorted["mean_shap"]]\n'
'axes[1].barh(shap_sorted["feature"], shap_sorted["mean_shap"], color=colors_shap)\n'
'axes[1].axvline(0, color="black", linewidth=0.8)\n'
'axes[1].set_title("Mean SHAP Values (LinearExplainer)", fontsize=12)\n'
'axes[1].set_xlabel("Mean SHAP Value")\n'
'\n'
'plt.suptitle("Linear Model: Coefficients vs SHAP Values", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'# SHAP summary plot for linear model\n'
'plt.figure()\n'
'shap.summary_plot(shap_values_lr, X_test.iloc[:1000], show=False)\n'
'plt.title("SHAP Summary Plot -- Linear Regression", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()'
))

# ── Cell 31: Section 10 - KernelExplainer (markdown) ──────────────────────────
cells.append(md(
'---\n'
'## 10. KernelExplainer (Model-Agnostic)\n'
'\n'
'`shap.KernelExplainer` is a **model-agnostic** SHAP implementation. It works with **any** '
'model that accepts a feature matrix and returns predictions -- SVMs, neural networks, '
'pipelines, custom models, API calls, etc.\n'
'\n'
'### How It Works\n'
'\n'
'KernelExplainer uses a weighted linear regression to approximate Shapley values:\n'
'1. Samples coalitions (feature subsets) using a Shapley kernel\n'
'2. Evaluates the model on these coalitions (masking features with background values)\n'
'3. Fits a local linear model that satisfies the SHAP axioms\n'
'\n'
'### Performance Considerations\n'
'\n'
'| Aspect | Details |\n'
'|--------|---------|\n'
'| Speed | **~100-1000x slower** than TreeExplainer |\n'
'| Background | Use `shap.sample(X_train, 100)` -- more = accurate but slower |\n'
'| `nsamples` | Controls coalition samples per explanation (default: `2*n_features + 2048`) |\n'
'| Parallel | Set `n_jobs` in the explainer call |\n'
'\n'
'**Rule:** Use KernelExplainer only when TreeExplainer or LinearExplainer are not applicable.'
))

cells.append(code(
'# Train a RandomForest (works fine with TreeExplainer, but we demo KernelExplainer here)\n'
'rf_model = RandomForestRegressor(\n'
'    n_estimators=50,  # fewer trees for speed\n'
'    max_depth=6,\n'
'    random_state=42,\n'
'    n_jobs=-1\n'
')\n'
'rf_model.fit(X_train, y_train)\n'
'\n'
'y_pred_rf = rf_model.predict(X_test)\n'
'rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))\n'
'print(f"RandomForest RMSE: {rmse_rf:.4f}")\n'
'print(f"RandomForest R2:   {r2_score(y_test, y_pred_rf):.4f}")\n'
'\n'
'# KernelExplainer requires a background dataset (use a small sample)\n'
'background = shap.sample(X_train, 100)\n'
'print(f"\\nBackground dataset size: {background.shape}")\n'
'\n'
'explainer_kernel = shap.KernelExplainer(\n'
'    rf_model.predict,  # any callable: model.predict, model.predict_proba, etc.\n'
'    background\n'
')\n'
'\n'
'print("KernelExplainer created. Computing SHAP values for 50 samples...")\n'
'print("(KernelExplainer is ~100x slower than TreeExplainer -- be patient!)")'
))

cells.append(code(
'# Compute kernel SHAP values for a small subset\n'
'n_kernel_samples = 50\n'
'shap_values_kernel = explainer_kernel.shap_values(\n'
'    X_test.iloc[:n_kernel_samples],\n'
'    nsamples=512  # coalition samples per explanation (lower = faster, less accurate)\n'
')\n'
'\n'
'print(f"Kernel SHAP values shape: {shap_values_kernel.shape}")\n'
'\n'
'# Summary plot\n'
'plt.figure()\n'
'shap.summary_plot(\n'
'    shap_values_kernel,\n'
'    X_test.iloc[:n_kernel_samples],\n'
'    plot_type="bar",\n'
'    show=False\n'
')\n'
'plt.title("SHAP Feature Importance -- KernelExplainer (RandomForest)", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'# Compare TreeExplainer vs KernelExplainer rankings\n'
'tree_ranks = mean_abs_shap.rank(ascending=False).astype(int)\n'
'kernel_mean_abs = pd.Series(\n'
'    np.abs(shap_values_kernel).mean(axis=0),\n'
'    index=X_test.columns\n'
')\n'
'kernel_ranks = kernel_mean_abs.rank(ascending=False).astype(int)\n'
'\n'
'comparison = pd.DataFrame({\n'
'    "TreeExplainer_rank": tree_ranks,\n'
'    "KernelExplainer_rank": kernel_ranks\n'
'}).sort_values("TreeExplainer_rank")\n'
'\n'
'print("\\nFeature Rank Comparison (TreeExplainer vs KernelExplainer):")\n'
'print(comparison.to_string())'
))

# ── Cell 34: Section 11 - Classification (markdown) ───────────────────────────
cells.append(md(
'---\n'
'## 11. SHAP for Classification\n'
'\n'
'For classification, SHAP values represent the contribution of each feature to the **log-odds** '
'(for tree models with `output_type="margin"`) or **probability** of each class.\n'
'\n'
'### Binary Classification\n'
'- SHAP values shape: `(n_samples, n_features)` for the positive class\n'
'- Or: `(n_samples, n_features, 2)` if `output_type="probability"` on both classes\n'
'\n'
'### Multi-Class Classification\n'
'- SHAP values shape: `(n_samples, n_features, n_classes)`\n'
'- Index class with `shap_values[:, :, class_idx]`\n'
'\n'
'### Interpreting Classification SHAP Values\n'
'- Positive SHAP value for class $k$ = feature pushes prediction **toward** class $k$\n'
'- Negative SHAP value for class $k$ = feature pushes prediction **away from** class $k$\n'
'- Base value = log-odds of class $k$ in the training set (prior probability)\n'
'\n'
'We use a **synthetic classification dataset** for this section to demonstrate multi-class handling.'
))

cells.append(code(
'# Create synthetic classification dataset\n'
'X_cls, y_cls = make_classification(\n'
'    n_samples=5000,\n'
'    n_features=10,\n'
'    n_informative=6,\n'
'    n_redundant=2,\n'
'    n_classes=2,\n'
'    random_state=42\n'
')\n'
'\n'
'feature_names_cls = [f"feature_{i}" for i in range(X_cls.shape[1])]\n'
'X_cls_df = pd.DataFrame(X_cls, columns=feature_names_cls)\n'
'\n'
'X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(\n'
'    X_cls_df, y_cls, test_size=0.2, random_state=42\n'
')\n'
'\n'
'# Train XGBoost classifier\n'
'xgb_cls = xgb.XGBClassifier(\n'
'    n_estimators=150,\n'
'    max_depth=4,\n'
'    learning_rate=0.1,\n'
'    use_label_encoder=False,\n'
'    eval_metric="logloss",\n'
'    random_state=42,\n'
'    n_jobs=-1\n'
')\n'
'xgb_cls.fit(X_train_cls, y_train_cls)\n'
'\n'
'from sklearn.metrics import accuracy_score, roc_auc_score\n'
'y_pred_cls = xgb_cls.predict(X_test_cls)\n'
'y_pred_proba = xgb_cls.predict_proba(X_test_cls)[:, 1]\n'
'print(f"Classifier Accuracy: {accuracy_score(y_test_cls, y_pred_cls):.4f}")\n'
'print(f"Classifier ROC-AUC:  {roc_auc_score(y_test_cls, y_pred_proba):.4f}")'
))

cells.append(code(
'# Create TreeExplainer for classifier\n'
'explainer_cls = shap.TreeExplainer(xgb_cls)\n'
'\n'
'# Compute SHAP values (returns Explanation object)\n'
'shap_values_cls = explainer_cls(X_test_cls.iloc[:500])\n'
'\n'
'print(f"SHAP values shape: {shap_values_cls.values.shape}")\n'
'print(f"Base value(s): {explainer_cls.expected_value}")\n'
'\n'
'# For binary XGBoost classifier:\n'
'# shap_values_cls.values has shape (n_samples, n_features)\n'
'# representing log-odds contributions for the positive class\n'
'\n'
'# Summary plot for positive class\n'
'plt.figure()\n'
'shap.summary_plot(\n'
'    shap_values_cls,\n'
'    X_test_cls.iloc[:500],\n'
'    show=False\n'
')\n'
'plt.title("SHAP Summary Plot -- Binary Classification (Positive Class)", fontsize=13)\n'
'plt.tight_layout()\n'
'plt.show()'
))

cells.append(code(
'# Waterfall plot for a misclassified sample\n'
'y_pred_all = xgb_cls.predict(X_test_cls.iloc[:500])\n'
'y_true_all = y_test_cls[:500]\n'
'\n'
'# Find misclassified samples\n'
'misclassified = np.where(y_pred_all != y_true_all)[0]\n'
'\n'
'if len(misclassified) > 0:\n'
'    mc_idx = misclassified[0]\n'
'    print(f"Misclassified sample index: {mc_idx}")\n'
'    print(f"  True label: {y_true_all[mc_idx]}")\n'
'    print(f"  Predicted:  {y_pred_all[mc_idx]}")\n'
'    print(f"  Probability of class 1: {xgb_cls.predict_proba(X_test_cls.iloc[[mc_idx]])[0, 1]:.4f}")\n'
'    print()\n'
'\n'
'    shap.waterfall_plot(shap_values_cls[mc_idx], show=False)\n'
'    plt.title(f"Waterfall -- Misclassified Sample (true={y_true_all[mc_idx]}, pred={y_pred_all[mc_idx]})",\n'
'              fontsize=12)\n'
'    plt.tight_layout()\n'
'    plt.show()\n'
'else:\n'
'    print("No misclassified samples in first 500 -- model is accurate!")\n'
'    shap.waterfall_plot(shap_values_cls[0], show=False)\n'
'    plt.title("Waterfall Plot -- Classification Sample 0", fontsize=12)\n'
'    plt.tight_layout()\n'
'    plt.show()'
))

# ── Cell 38: Section 12 - Best Practices (markdown) ───────────────────────────
cells.append(md(
'---\n'
'## 12. Production Tips & Best Practices\n'
'\n'
'### Choosing the Right Explainer\n'
'\n'
'| Situation | Recommended Explainer | Notes |\n'
'|-----------|----------------------|-------|\n'
'| Tree models (XGB, LGB, RF, CatBoost) | `TreeExplainer` | Exact, fast, always use this |\n'
'| Linear models (Ridge, Lasso, LogReg) | `LinearExplainer` | Exact, handles correlations |\n'
'| Any model, debugging/exploration | `KernelExplainer` | Slow, approximate -- sample background |\n'
'| Neural networks | `DeepExplainer` or `KernelExplainer` | DeepExplainer for TensorFlow/Keras |\n'
'\n'
'### Which Plot to Use\n'
'\n'
'| Goal | Plot |\n'
'|------|------|\n'
'| Global feature importance | Summary plot (bar) |\n'
'| Global feature effects + direction | Summary plot (beeswarm) |\n'
'| Single prediction explanation | Waterfall or Force plot |\n'
'| Non-linear effects of a feature | Dependence plot |\n'
'| Feature interactions | Dependence plot with `interaction_index` or Interaction matrix |\n'
'| Production monitoring | Mean absolute SHAP values over time |\n'
'\n'
'### Performance Tips\n'
'\n'
'1. **Always use `TreeExplainer` for tree models** -- it is orders of magnitude faster than KernelExplainer\n'
'2. **Background sample for KernelExplainer**: `shap.sample(X_train, 100)` is usually sufficient\n'
'3. **Batch SHAP computations**: Compute once for a dataset, cache results\n'
'4. **Memory for interaction values**: O(n_samples * n_features^2) -- use < 500 samples\n'
'5. **GPU acceleration**: XGBoost with `device="cuda"` supports fast SHAP on GPU\n'
'\n'
'### Common Pitfalls\n'
'\n'
'| Pitfall | Fix |\n'
'|---------|-----|\n'
'| SHAP values do not sum to prediction | Check `expected_value` -- use `explainer.expected_value`, not 0 |\n'
'| Multi-class SHAP shape confusion | Shape is `(n_samples, n_features, n_classes)` -- index the class |\n'
'| KernelExplainer too slow | Reduce `nsamples`, use smaller background |\n'
'| Interaction values OOM | Reduce sample size, use 32-bit floats |\n'
'| SHAP for probability vs log-odds | Set `model_output="probability"` in TreeExplainer if needed |\n'
'\n'
'### Regulatory & Audit Use Cases\n'
'\n'
'SHAP is widely used for:\n'
'- **Credit scoring explainability** (EU AI Act, GDPR "right to explanation")\n'
'- **Healthcare model auditing** (FDA AI/ML guidelines)\n'
'- **Bias detection** (check if protected features have high SHAP values)\n'
'- **Model debugging** (identify training data artifacts via anomalous SHAP patterns)'
))

cells.append(code(
'# Production monitoring example: track mean |SHAP| over time\n'
'# Simulate concept drift by splitting test set into batches\n'
'\n'
'batch_size = 100\n'
'n_batches = 5\n'
'batch_shap_means = []\n'
'\n'
'for batch_idx in range(n_batches):\n'
'    start = batch_idx * batch_size\n'
'    end = start + batch_size\n'
'    X_batch = X_test.iloc[start:end]\n'
'\n'
'    sv_batch = explainer(X_batch)\n'
'    mean_abs = np.abs(sv_batch.values).mean(axis=0)\n'
'    batch_shap_means.append(mean_abs)\n'
'\n'
'batch_df = pd.DataFrame(\n'
'    batch_shap_means,\n'
'    columns=X_test.columns,\n'
'    index=[f"Batch {i+1}" for i in range(n_batches)]\n'
')\n'
'\n'
'# Plot SHAP stability across batches\n'
'fig, ax = plt.subplots(figsize=(12, 5))\n'
'batch_df.T.plot(kind="bar", ax=ax, colormap="viridis")\n'
'ax.set_title("Mean |SHAP| Stability Across Batches (Production Monitoring)", fontsize=13)\n'
'ax.set_xlabel("Feature")\n'
'ax.set_ylabel("Mean |SHAP Value|")\n'
'ax.legend(title="Batch", bbox_to_anchor=(1.0, 1.0))\n'
'plt.xticks(rotation=45, ha="right")\n'
'plt.tight_layout()\n'
'plt.show()\n'
'\n'
'print("\\nMean |SHAP| per batch (production drift monitoring):")\n'
'print(batch_df.round(4).to_string())'
))

# ── Cell 40: Closing / Portfolio Addendum ─────────────────────────────────────
cells.append(md(
'---\n'
'## Key Takeaways\n'
'\n'
'1. **SHAP is the gold standard** for ML explainability -- grounded in game theory with theoretical guarantees\n'
'2. **TreeExplainer is your go-to** for XGBoost, LightGBM, and RandomForest -- fast and exact\n'
'3. **Beeswarm plots** reveal global feature effects with direction; **bar plots** give clean summaries\n'
'4. **Waterfall and force plots** debug individual predictions -- essential for model auditing\n'
'5. **Dependence plots** expose non-linear effects and feature interactions without overfitting assumptions\n'
'6. **KernelExplainer is model-agnostic** -- use it as a last resort when no specialized explainer applies\n'
'7. **SHAP enables production monitoring** -- track mean |SHAP| over time to detect concept drift\n'
'\n'
'---\n'
'\n'
'## Portfolio Quality Addendum\n'
'\n'
'**Objective:** Demonstrate end-to-end SHAP usage for both regression and classification tasks '
'using publicly available sklearn datasets, with no external data dependencies.\n'
'\n'
'**Data:** California Housing dataset (sklearn.datasets) for regression; `make_classification` '
'for binary classification. Both are fully reproducible with fixed `random_state=42`.\n'
'\n'
'**Method:** Progressive complexity -- TreeExplainer (fast, exact) → LinearExplainer (linear models) '
'→ KernelExplainer (model-agnostic). Each explainer demonstrated with multiple visualization types.\n'
'\n'
'**Evaluation:** Local accuracy verified algebraically: `base_value + sum(SHAP) == prediction`. '
'Production monitoring simulated with batch-wise mean |SHAP| tracking.\n'
'\n'
'**Insight:** `MedInc` dominates California Housing predictions. Its dependence plot shows a '
'non-linear saturation effect: high income increases predicted house value, but the marginal '
'SHAP effect diminishes at very high incomes. Geographic features (`Latitude`, `Longitude`) '
'have strong interactions.\n'
'\n'
'**Trade-off:** KernelExplainer achieves model-agnosticism at the cost of ~100-1000x slower '
'computation. For production systems with tree models, always use TreeExplainer. For neural '
'networks, DeepExplainer or a cached KernelExplainer with batching is preferred.\n'
'\n'
'---\n'
'\n'
'## Conclusion and Next Steps\n'
'\n'
'You now have a comprehensive SHAP toolkit. Next steps:\n'
'\n'
'- **Apply SHAP to your own competition models** -- always include an explainability section in notebooks\n'
'- **Explore `shap.DeepExplainer`** for PyTorch/TensorFlow neural networks\n'
'- **Build SHAP-based monitoring dashboards** with Streamlit or Gradio\n'
'- **Read the original paper**: Lundberg & Lee, "A Unified Approach to Interpreting Model Predictions" (NeurIPS 2017)\n'
'- **SHAP GitHub**: https://github.com/slundberg/shap\n'
'- **SHAP Docs**: https://shap.readthedocs.io/\n'
'\n'
'---\n'
'\n'
'*If you found this notebook useful, please give it an **upvote** -- it helps others in the Kaggle community discover it!*\n'
'\n'
'*Questions or suggestions? Leave a comment below.*'
))

# ── Assemble and write notebook ────────────────────────────────────────────────

write_notebook(cells, __file__, "shap_explainability_guide.ipynb")
